### ISSUE TITLE
The move to seperate jobs files has removed all comments form example woodcutter job

### ISSUE THREAD

**Issue by Klawdek** [Zrips/Jobs#1055]
***Description of issue:**
After upgrading to 4.17.0 where all jobs were moved to separate files including the example job of woodcutter, all comments have been removed from the example jobs rendering that file not as useful.  
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
https://pastebin.com/D8mswnWZ
---
Note that not one comment is in the example file.

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-400 (MC: 1.16.4)

**Comment by montlikadani** [comment]
That's why have github to store default files and codes. https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/_EXAMPLE.yml

**Comment by Klawdek** [comment]
So if someone does a new installation of jobs with no prior version present they will still get the backups with the example that has a description? If so that is in odd place to look for comments on example job.  The comments should be in the example job file.

**Comment by montlikadani** [comment]
Because we recently moved the jobs to separate files, the old jobConfig file remains as a backup. However, this file is no longer used by the plugin, so it generates as many jobs files in the Jobs directory as it previously had in the jobConfig file. This jobs directory contains a _EXAMPLE file for current jobs, which also contains default jobs, examples, and comment descriptions.
