### ISSUE TITLE
Adding event listeners to the API

### ISSUE THREAD

**Issue by DevGalacticB69** [Zrips/Jobs#1070]
# **Adding event listeners to the API**

I simply want a way to be able to easily get information regarding job actions for use in my plugin.

Proposed method format:
`getEvent(player, eventType, captureTime, additonalArgs)`

### **Player Object**
The argument _player_ is kinda obvious. (Return an error if not registered)

### **Event Type**
_eventType_ can be one of the following types:

- Break
- StripLogs 
- TNTBreak
- Place
- Kill
- MMKill
- Fish
- Craft
- VTrade
- Smelt
- Brew
- Enchant
- Repair
- Breed
- Tame
- Dye
- Shear
- Milk
- Explore
- Eat
- custom-kill
- Collect
- Bake

## _Capture Time_  
Ideally, this value would be the amount of time you wish to collect information for the specific event type.
Basically when this method is called it records the requested information for x amount of ticks and returns that info as the return value.

**Example:** 
So let's say we wanted to see if the player smelted anything in the last 30 seconds it would be as following:

`getEvent(player, Smelt, 600);`

### **Additional Return Information**

This is a big ask but returning additional information such as what item was repaired or what animal was tamed would be really awesome! 

Here's a list of possible additional information to return for each action:

- Break (blocks broken)
- StripLogs (log type)
- TNTBreak (blocks broken)
- Place (blocks placed)
- Kill (entity killed)
- MMKill (MMentity killed)
- Fish (item caught)
- Craft (item crafted)
- VTrade (IDK what this is lol)
- Smelt (Item Smelted)
- Brew (potion brewed, potion strength)
- Enchant (item enchanted, enchant applied)
- Repair (Item repaired)
- Breed (entity bred)
- Tame (entity tamed)
- Dye (item dyed)
- Shear (sheep color)
- Milk (entity milked)
- Explore (region explored)  (additional argument: corner1,corner2 [square chunk area between 2 points])
- Eat (item used)
- custom-kill (entity killed)
- Collect (item collected)
- Bake (item baked)

A lot of these might actually have to be lists now that I think about it. 

If anyone has any suggestions on how to better improve this concept, please comment them!

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/ActionType.java, with this enum use `Enum#values` to get an array of fields

Called built-in plugin events:
https://github.com/Zrips/Jobs/wiki/API

**Comment by DevGalacticB69** [comment]
Yes, but the goal was to record and test for players actively doing a specific job, and or a specific event in said job. If I wanted to do it by calling all of the individual classes I would have already done it in that manner. However, I do not have the amount of time to read the entirety of the undocumented code which has no javadocs or annotations. Before you quote the file from which I got the action types, please consider that I myself and others may not be able to utilize that method in an effiecent way.

**Comment by montlikadani** [comment]
I don't see the point. There should be no additional memory leak scheduling tasks in the Jobs project, as it uses quite a bit of memory and performance, even asynchronously. And this shouldn’t be solved in Jobs either, but in his own project. What I linked to earlier, you can use the Jobs API events to listen to various events that Jobs calls. On the other hand, what is `getEvent` method? Perhaps it would suggest that Jobs will call a method for each job done when events already exist? Or maybe you think Jobs will invoke a method that can only be solved with DI (Dependency Injection) or reflections?

By avoiding all this, you can solve this as follows in this example: 
- Outside the method, store an interface called `Cache` with the appropriate parameters. It will store the information for a specified interval.
- Initialize this field with `CacheBuilder.newBuilder()` and specify an expiration time to clear the stored information about the player from memory after writing or reading. 
- Then listen to JobsPrePaymentEvent to find out which player and what thing they did in a job.

The code for this looks like:
```java
private Cache<UUID, JobsPlayer> playerCache;

public JobsPlayer getCachedPlayerInformations(UUID playerUUID) {
  return playerCache != null ? playerCache.getIfPresent(playerUUID) : null;
}

public void addPlayerCache(UUID uuid, JobsPlayer who) {
  // This will expires after 30 seconds and after write
  playerCache = CacheBuilder.newBuilder().expireAfterWrite(30, TimeUnit.SECONDS).build();

  // Now we caches the given player into memory
  playerCache.put(uuid, who);
}

@EventHandler
public void onJobsPayment(JobsPrePaymentEvent event) {
  if (getCachedPlayerInformations(event.getPlayer().getUniqueId()) == null) {
    addPlayerCache(event.getPlayer().getUniqueId(), Jobs.getPlayerManager().getJobsPlayer(event.getPlayer.getUniqueId()));
  }

  // Do your capture time thing
}
```

About the undocumented code: since there are a lot of classes, methods, and everything else in the Jobs project that should be documented, this is likely to happen later. Anyway, what’s so hard about looking at what returns a value back to a method, assuming you use it somewhere in your own project? This project was not written with complex and difficult abstraction to make the project code difficult to see and read. Anyway, we welcome any PR (Pull Request) from anyone that we can merge.

**Comment by Geolykt** [comment]
I don't think that needlessly caching stuff is a good idea (such a method would only be called rarely) as it would mean that data is retained for longer than it should be, which would mean more memory consumption along other things. I also don't quite get your concept of `getEvent(player, Smelt, 600);`, should it return the last event that matches the specifications (or null) or something else?
