### ISSUE TITLE
value for 10L adjustable in generalconfig.yml

### ISSUE THREAD

**Issue by Serial1990** [Zrips/Jobs#1097]
Could you please make the value for the PlayerJointEvent delaytime "10L" for Multi-Server adjustable in the generalConfig.yml
Because for our Multi-Server the delay is to small, so if you change a server its not getting the latest JobsData from the DB, cause the savingprocess is not finished yet.

`@EventHandler(priority = EventPriority.HIGHEST)
    public void onPlayerJoin(final PlayerJoinEvent event) {
    if (!Jobs.getGCManager().MultiServerCompatability())
        Jobs.getPlayerManager().playerJoin(event.getPlayer());
    else {
        plugin.getServer().getScheduler().runTaskLater(plugin, () ->
            Jobs.getPlayerManager().playerJoin(event.getPlayer()), 10L);`

Line 165-171 in Jobs/src/main/java/com/gamingmesh/jobs/listeners/JobsListener.java

**Comment by montlikadani** [comment]
No, `PlayerJoinEvent` is only called when a player fully appeared in a specific server. There are other events called `PlayerSpawnEvent` or stg, that called before `PlayerJoinEvent`, so it makes no sense. We have to remove entirely the delay task instead.

**Comment by Serial1990** [comment]
so, thats sounds good. please add the same for the PlayerSpawnEvent. otherwise our players have problems with the jobs xp progress, if they are switching between the servers.

**Comment by montlikadani** [comment]
No, player's data will be loaded synchronously meaning that to freeze the main thread while the players data not loaded from database. We could improve this by implementing async Future, but we'll not do this as there are some methods which is not thread safe.

You have to enable `MultiserverCompatibility` in order to synchronize the player's data to another server through MySql database. Also, players experience and other things related to it, will be loaded for specific player if they joined to a server, and currently there is no any issues with experience loading as it works for me.

What you described before, increasing the delay within the task, just decreases the server performance, resulting to make unneeded timings reports.
