### ISSUE TITLE
Incorrect display of names on version 1.12.2

### ISSUE THREAD

**Issue by Thin-Troll** [Zrips/Jobs#1105]
***Description of issue:**

https://github.com/Zrips/Jobs/issues/1092

![image](https://user-images.githubusercontent.com/61376903/110220866-7e385480-7eea-11eb-9ea5-922aa7a5991f.png)
![image](https://user-images.githubusercontent.com/61376903/110220974-1df5e280-7eeb-11eb-86d3-3a1894588e72.png)

**Comment by montlikadani** [comment]
Well, I quess this expected behaviour? As during the testing I realized that these stained glasses does not have full color names according to the [1.12.2 API](https://helpch.at/docs/1.12.2/org/bukkit/Material.html#STAINED_GLASS). In TranslatableWords file, there are stained_glass with color names generated, but those names are not exist in minecraft 1.12.2.

**Comment by Zrips** [comment]
@Thin-Troll 
Double check your translatableWords file as this could originate from it as of some testing, everything seam to work as it should and correct names are shown
