### ISSUE TITLE
Big performance loose when you switch worlds

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Jobs#1113]
***Description of issue:**

---

Hi, I wanna report that even when I use default jobs settings (I tried remove all plugins and then just regenerate whole Jobs folder), I'm getting these BIG TPS SPIKES by spark, this was highlighted me by Luck from LuckPerms: https://spark.lucko.me/60I0727oXJ?hl=9949,14865,42,23,37697
![image](https://user-images.githubusercontent.com/18662086/111164549-76d61280-859e-11eb-94a2-1efad745f274.png)

It doesn't seem to be related to Jobs on the first point of view, but it is. Cause i've tested yesterday switching worlds from 
https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-the-nether-and-the-end-support-expiration-1-8-1-16-4.72113/, but maybe the problem is switching between every world, but probably not so big.

So when I've tested it yesterday, I've tested it on two servers. (now both of them use Tuinity, before one of them had Yatopia, but this wasn't cause):
https://spark.lucko.me/pMaNs6uQ7v -> first server, yo ucan see there bukkitCreate event with jobs
https://spark.lucko.me/SF2qwhH2AS -> second server -> without jobs

Then I've tried switch from Yatopia to Tuinity on the first server, it didn't help. Then I've tried remove all plugins except playerworlds and it helped. Instead of 800ms there was max 200/300ms like on the second server when switching worlds. So I've tried add some plugins few by few... And then I discovered that the SOURCE of these lag spikes is Jobs plugin. Really, I've tried it without this single plugin and there weren't these spikes on switching worlds.  These spikes happen very often for me, when someone switch to world, and I will be glad if you could solve it.

And just btw worlds aren't created... I'm just teleporting to them... they are already created... so I just switch to them, IDK why it's named bukkit create world event

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):** PlayerWorldsPro (but may isn't needed, the problem is when switching worlds)

Jobs version: The newest dev from Discord

**Comment by montlikadani** [comment]
And what can we do with it, or how can we improve it? There is no `Bukkit.createWorld` method in the Jobs code at all, which would degrade performance somewhat. From this spark report, I can only see that the `Bukkit.createWorld` method has a high CPU load time, which I think the chunk loading is slow as a "habit". Looking more closely into this method in the spark viewer, I found about 3 resources/plugins that only have a CPU load time of between 0.1-0.8, which is not a huge amount. I looked in all three spark reports, with the newer Spark release I filtered these results for Jobs, but I couldn’t find one for Jobs that would burden CPU usage because the results are similar, ranging from 1 to 8 milliseconds, which is again not a huge result.

In the Jobs code, only one Bukkit event is called to change the world that is likely to have little performance, this
https://github.com/Zrips/Jobs/blob/e502fa4ab5608a595dfdffdd299adad13a7642ed/src/main/java/com/gamingmesh/jobs/listeners/JobsListener.java#L179-L182

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/111876793-ab800a80-89a0-11eb-9b50-9a86ea92dea8.png)
And this one doesn't mean nothing weird? https://spark.lucko.me/pMaNs6uQ7v

But really when I've tried to remove Jobs there were max 300ms on teleport, not 800 like before. But if you don't know what could cause it, then we could probably close it.

**Comment by montlikadani** [comment]
It seems that adding the permission in the `WorldLoadEvent` method takes a long time to add to LuckPerms.

![kép](https://user-images.githubusercontent.com/30026208/111876970-5c86a500-89a1-11eb-95d9-edea688092b9.png)
At least I can't do much in this situation. Adding permissions is added to the permission resource properly using the Bukkit API, so we don't have to add each plugin individually as a dependency. These permissions are required for players to have proper permission to pay for jobs individually. We only use these two lines of methods to add permissions:
https://github.com/Zrips/Jobs/blob/0d138d66645840435d261bfe7c784925f6253a67/src/main/java/com/gamingmesh/jobs/listeners/JobsListener.java#L354-L355

To tell you the truth, there aren’t too many ideas on how to improve in Jobs. There is only one thing that can be done to report this to the author LuckPerms and attach the above ^ smaller code as evidence or send him a the link of this comment.

**Comment by bobhenl** [comment]
Ok, I've created issue there, thanks.
