### ISSUE TITLE
Support custom fish

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#1116]
Is it possible to add support for this plugin: https://www.spigotmc.org/resources/pyrofishingpro-1-14-x-1-16-x-1-fishing-plugin.60729/
Or is it already possible to define a fish by its "name"? A bit like MythicMobs but a fisherman version :)

**Comment by montlikadani** [comment]
Looking at the resource, I didn’t see any free available APIs or documentation that we could possibly use to create compatibility using the plugin. To avoid a flat jar, we would need a constantly running repository for the resource so that we can use any modified API methods in the future and not have a problem. If that author creates a repository handler and makes the API free for other developers, we'll add it later if someone suggests it again.
