### ISSUE TITLE
4.17.2 - colored names broke nick with hex)

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1141]
![image](https://user-images.githubusercontent.com/12080017/113410009-b67c6700-93b2-11eb-87c1-41ea59238ea7.png)

In the 1.17.2 Version colored nickames broke

**Comment by montlikadani** [comment]
1.17.2? Did you got future MC release maybe? Also, those hex colors are not supported in there, Jobs uses CMI's hex colors, https://www.zrips.net/cmi/hex-colors

**Comment by CloudeLecaw** [comment]
This id 1.17.1 versionnall is fine! I using cmi long time now. And im confirmal with the hex cmi uses. All is fine with Version 1.17.1 the Problem comes with the new dev Version 1.17.2 rhat rhe hexnane is shown in thus incorect way.
We use the dev Version 1.17.2 from Discord. This ine solves a Problem where our players are getting random jobs for nonreason ( and loosing their iod job).
No matter what went erst ng in the 1.17.1  we allready reseted the whole database to make sure that its.ni database problem.  We are using sqlite.

**Comment by montlikadani** [comment]
Good try? What do I mean by that? Maybe some kind of anger, abuse, or maybe something other than the issue? As if I were his slave again. For some reason, I have to write a novel at least once every 1 month because the “crazy” kid seems to see it as dismissive or slavish. I feel like I have to leave this whole Minecraft here because of this. I'm getting bored. The other thing is, why does everyone praise that developer version 1.17.2 and think this is right? Maybe you uploaded that version? I don't see a post that includes this version. At least I only see 4.17.2.
**Anyway, let's get back to this issue.** So, ignoring your spelling problems, is your problem that the color codes in the chat aren’t working properly that would contain the hex color? Well, this _Adventure_ recently came out on _Paper_, which somewhat breaks down some resources, especially when used as well. I followed this too and the chat alone did not work properly. But I have already reverted this change to the old one so that we can also support chat format changes. [This commit](https://github.com/Zrips/Jobs/commit/e502fa4ab5608a595dfdffdd299adad13a7642ed#diff-1bfbe6e687df3d25184129d03a872214701ccaa42c802d868cdf071f87dbfb32) shows that I reverted to the old player chat event method and the developer version includes this commit. Based on the test, this worked with a basic prefix setting. By this I mean that it did not include a hex color format, but a default that was created during configuration generation. Maybe you changed something in one of the Jobs configurations afterwards? Especially in generalConfig? Because this file contains settings for the chat prefix to change the chat format to a specified one. Of course, if it is not overwritten in a dependency resource such as EssXChat or CMI. If you may have done so, check and make sure it is correct.

**Comment by CloudeLecaw** [comment]
we changed nothing from 1.171 to 1,17,2 we just replaced the jar file nothing else

**Comment by montlikadani** [comment]
Is this still reproducible with the updated release in `#dev-releases` channel on discord?

**Comment by CloudeLecaw** [comment]
i dont know if there was a new 1.17.2 in the dev channel but i redownloaded it and tested agggain. the result is the same :(

![image](https://user-images.githubusercontent.com/12080017/113913943-381e2b80-97dd-11eb-80b2-da95b9aad857.png)

for coloring the name i used CMIS nick command

` /cmi nick {#cc2500>}Cloude{#e68773<>}_Lecaw{#e6c8b8<} Cloude_Lecaw`  i dont know if i used these hexes colorcodes or others but thats the commands i used for the nick. the colorcodes i took from cmis colorpicker :)

![Snag_1886c15](https://user-images.githubusercontent.com/12080017/113914210-93501e00-97dd-11eb-84b4-2b34a89ec34b.png)

**Comment by Zrips** [comment]
ed9fe4d26ec4e518204e10ccebbebb40c0a60263

**Comment by CloudeLecaw** [comment]
Just wanne tell the nicks in Jobs are still broken

![Snag_3c532d](https://user-images.githubusercontent.com/12080017/117207258-102de200-adf4-11eb-8fe0-129268c89f65.png)
