### ISSUE TITLE
Shop Option: HideWithoutPermission

### ISSUE THREAD

**Issue by JustDriessen** [Zrips/Jobs#1180]
Delete please

**Comment by montlikadani** [comment]
Then the players will not be able to buy or click on any items because the `HideWithPermission` option prevents to buy things from shop. So if players have permission to buy a item from shop, and the `HideWithPermission` is enabled then they will not be able to buy anything, despite they have the correct permissions.

> to making an upgrade system with it, this needs the option that I asked for above to make it that way. So players can't accidently purchase the upgrade twice.

For your "upgrade system" use a gui shop plugin which doing that.
