### ISSUE TITLE
Sometimes decimal places setting is ignored

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#1289]
***Detailed description of the issue:**

Hey, it looks like sometimes the configuration setting of two decimal places is ignored, for example when using a command like:

`jobs level mrfloris Miner add 2`

<img width="960" alt="Screenshot 2021-10-03 at 06 49 37" src="https://user-images.githubusercontent.com/28841349/135740428-bd84ef8c-c269-4459-8f7b-3d06a5f1cee0.png">
```
> ver
[06:51:41 INFO]: Checking version, please wait...
[06:51:41 INFO]: This server is running Paper version git-Paper-295 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f905057)
You are 5 version(s) behind
Previous version: git-Paper-293 (MC: 1.17.1)
> jobs version
[06:51:47 INFO]: --------------------------------------------------
[06:51:47 INFO]: Jobs: 5.0.0.8 SqLite
[06:51:47 INFO]: CMILib: 1.0.3.11
[06:51:47 INFO]: Server: Paper(295) 1.17.1-R0.1-SNAPSHOT
[06:51:47 INFO]: Economy: CMIEconomy Vault: 1.7.3-b
[06:51:47 INFO]: --------------------------------------------------
>
```

```yaml
  DecimalPlaces:
    # Decimal places to be shown
    Money: 2
    Exp: 2
    Points: 2
```

<img width="904" alt="Screenshot 2021-10-03 at 06 52 44" src="https://user-images.githubusercontent.com/28841349/135740458-e9be02cc-fe1a-43c4-9a36-7dd92f631812.png">

**Comment by zhgt** [comment]
Hi there. I speak Spanish, if it is not understood correctly it is because I use a translator.

I am Fufu in discord.

What I'm trying to do is give an award by voting using votingplugin. When voting, use the command /jobs level %player% %jobsr_user_job_1% add 2 to detect the first job that the user and the player have. It works fine but as I mentioned earlier, it appears with many decimal places.

From what I verified, it only happens with this command since if I use /jobs stats, it appears with 2 decimal places correctly as it is in the configuration.

Jobs version: 5.0.0.8 
Paper: 1.16.5-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
71d24aa7dc1a62ea3d981287de95653775908923
