### ISSUE TITLE
/jobs blockinfo no works as expected

### ISSUE THREAD

**Issue by Skjolberg** [Zrips/Jobs#1311]
***Detailed description of the issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->

When using "/jobs blockinfo" it doesn't give me the expected results, in block data it says 0 (I don't know what data should be displayed, but I doubt that 0 is expected, all the blocks return the same value) then in Usage: in the configuration there are 2 variables but it only shows in the game the value of 1 of them which is the block, I think that this part of blockinfo is not working as it should.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

https://i.ibb.co/59ZwxYM/9ae0efa4a7f5cd5f4e4c47706f520b95.png

---

**Jobs version: Last, 5.0.0.9** 

**Server Type (Spigot/Paper/etc): Airplane-Púrpur** 

**Server Version (using `/ver`): 1.16.5**

**Comment by Zrips** [comment]
It just some what outdated, due to changes with recent minecraft versions some of the data became deprecated, now you simply need to use material name and in some rare situations state of that block, like fully grown wheat would be wheat-7 where value 7 indicates stage of growth, in most cases you dont need to add 0 unless you only want to give out money when block state is at 0 specifically, like giving negative income if you brake just planted wheat and give positive income when its fully grown. 
Will update output of this command to be more user friendly.
