### ISSUE TITLE
Default configured Job Miner won't pay when axe Y < 0 

### ISSUE THREAD

**Issue by OwerGrowen** [Zrips/Jobs#1340]
### Detailed description of the issue:

This Bug/Unimplementation was discovered by a Player who joined the Default configured Job **Miner** and did not receive any earnings from the Job itself for mining in the new Caves.

With the 1.18 Update the new caves are below Y:0 so the axe Y can be negative. Therefor it seems the Plugin can not handle certain earnings or events when a Player mines blocks below Y:0. 
Maybe the other Jobs are affected aswell?

---

**Jobs version: 5.0.1.0** 

**Server Type (Spigot/Paper/etc): Spigot** 

**Server Version (using `/ver`): 1.18.1**

**Comment by CERIBES** [comment]
I don't think that is a y< 0 issue. On my server for example i get xp and money for mining obsidian above y:0 and at y:-60.
I think the issue is in your config miner.yml you don't have the blocks listed. have this issue with some blocks on my sever. The default config files don't include all of the blocks and none for 1.18.

**Comment by Zrips** [comment]
Block brake event isint checking by Y in general, so there should not be any issues relating to where exactly you broke that block as long as you actually did it.
