### ISSUE TITLE
[BUG] Could not load Jobs - spigot 1.18.1

### ISSUE THREAD

**Issue by ErythroCraft** [Zrips/Jobs#1343]
***Detailed description of the issue:**
Could not load Jobs after installing latest spigot server version.
---

####################
####################
```
 - https://pastebin.com/tXZQeq9A

**Jobs version: 5.0.1.0** 

**Server Type (Spigot): 3375-Spigot-8965a50-319ca70 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)** 
**These releases work around a security issue in log4j2, the logging library used by Minecraft.**

**Server Version (using `/ver`):** 

**Relevant plugins: 
 - CMILib
 - other**

https://pastebin.com/PC3Bu3kf

**Comment by ardmarel** [comment]
Unfortunately i have encountered the same issue. I just found out that deleting the exampleconfig works as workaround. Would you like to upload your example config file as I deleted mine. It might help to figure out if the issue is in the data being written by the plugin or the way CMIlib handles the file.

https://pastebin.com/PzYQb8zG

**Comment by Zrips** [comment]
Fixed with latest CMILib update
