### ISSUE TITLE
Farmer jobs paying for thrown chicken eggs

### ISSUE THREAD

**Issue by trevor1097** [Zrips/Jobs#1349]
**Detailed description of the issue:**
The farmer job is paying for eggs that are thrown and even from a dispenser, making it possible for to gain a lot of money exploiting a chicken farm. Is it possible to not pay for chickens that spawn from eggs?

The original ticket from someone else https://github.com/Zrips/Jobs/issues/1188#issue-898820140

---

**Jobs version:**  5.0.1.0

**Server Type (Spigot/Paper/etc):**  Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-121 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4bf2aef)

**Comment by Zrips** [comment]
Sadly there is no way to know who launched egg which caused entity to be spawned. We already using basic look up for closest player when entity spawns due to lack of API to know what source (player) caused this spawn event. Without directly blocking chicken egg dispensing from dispensers we will have to live with this possible exploit or simply avoid using chicken breeding as a way to make money.
