### ISSUE TITLE
On 1.18, you cannot middle-click to leave a job in /jobs browse.

### ISSUE THREAD

**Issue by codeHusky** [Zrips/Jobs#1365]
***Detailed description of the issue:***

When in the /jobs browse menu, you are unable to middle-click to leave a job, preventing users from easily leaving a job from the menu.

---

**Jobs version:** 5.0.1.1

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)
You are running the latest version
Previous version: git-Paper-75 (MC: 1.18.1)

**Comment by Zrips** [comment]
Yea, this is due to Mojang disabling middle mouse button on 1.18.1 when player is in survival mode and doesn't hold any item on cursor. There isint any real easy solution here, for time being will simply add Q key as optional one to leave job. Will introduce new locale line to properly reflect this new change.

**Comment by Zrips** [comment]
4b1e877368b437187cf2f7e3a26ba90944d6d039
