### ISSUE TITLE
Builder should include placing Deepslate, Blackstone etc.

### ISSUE THREAD

**Issue by tag** [Zrips/Jobs#1483]
Expand Builder job to include XP for placing Deepslate (+ cobbled, tiled, etc.) and Blackstone (+ variations)

**Comment by Zrips** [comment]
Anyone can add their own setup for specific block placement if needed. If we are talking about default builder job, then help in filling up missing materials for any job is welcome and would be really appreciated from anyone who has better understanding how rare and how much it should reward for placing those than I do myself.
If you have those entries you can ether submit commit here on gthub or send me PM over discord so that I could add those. Zrips#9691
