### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by DasKirschbrot** [Zrips/Jobs#150]
Hey
I am having the following problem:
Our idea of our job system was that the players should get specific permissions at joining a job.
But the plugin does not give the permissions to the player.
I do not know why this is the case, but thanks for you help.
Best regards,
Daniel.

Here is the part of the config.yml:
    
permissions:
      # example node
      modifyworld.blocks.destroy.log:
        # true to give, false to revoke
        value: true
        # minimum level needed to grant permission.  Use 0 for all levels
        level: 0
      modifyworld.items.craft.potion:
        value: true
        # Permission granted when reaching level 10
        level: 0

**Comment by montlikadani** [comment]
**Try update to the latest version.**

**Comment by montlikadani** [comment]
After a good while ... We realized (finally) that when Jobs registers new permission names, they can't be added by Bukkit, that is, they can't be integrated into the permission systems database, or the plugin can't accept them. This is not a fix, as a lot of data is still saved in Jobs causing server delays and will not be fixed. Otherwise, this Jobs plugin is not a permission handler, but a job handler.
