### ISSUE TITLE
Sand/Gravel gravity overrides/ignores restricted blocks

### ISSUE THREAD

**Issue by AsinineTyrant** [Zrips/Jobs#1554]
Sand and Gravel, when affected by gravity, become restricted for the default duration (a few seconds), even if they arent listed in restrictedblocks.yml. If they are listed, even with the duration set to 1 or 0, its still over-ridden by the default. I've seen this issue reported and fixed a few separate times so hopefully its just an oversight. Can provide more details if necessary but I figure its already a known issue. Thanks

Jobs version: 5.1.2.0
Server type: Paper
Server version: 1.19.2

**Comment by Zrips** [comment]
Gravity blocks are not being checked fully due to how heavy check like this could be and this generally only effects low priority blocks. There is default timer (3 seconds) for all blocks if its not present in restrictedBlocks.yml file. Will add option to disable this protection for defined blocks, even tho keeping it at 1 second should be running and giving some some small general protection.
