### ISSUE TITLE
Placeholder for %jobsr_jtop_name_[jname/number]_[[1-15]]%

### ISSUE THREAD

**Issue by KingCueio** [Zrips/Jobs#1608]
**Description of new idea or improvement on existing one**
Changing the "%jobsr_jtop_name_[jname/number]_[[1-15]]%'s result to be just the "In-Game Name" itself

**Detailed information what should do**
I tried using the placeholder, but it seems like it turns with this 
![image](https://github.com/Zrips/Jobs/assets/87959487/ae28407e-dde6-4987-9aaa-f7372eb121cc)

Even though the code for your placeholder is this:
![image](https://github.com/Zrips/Jobs/assets/87959487/718cbf54-776e-464e-a898-b830a499ee05)

Is there a possible way that to have an option whether it will have a "Preffix" or Change displayname or to just have In-Game Name itself?

**Comment by Zrips** [comment]
Its returning players display name as being defined by plugins which manages this part. Showing players actual name can work if you are not using nickname commands and players name remains same as his displayname, other than this you would need to adjust how players display name is being defined by plugin which manages it, basically we are showing same thing as you would see in tablist.
What I can do is to simply add new placeholder which would show players name instead of his displayname.
260470406e09060a93b0fda84dccdf0ac4e62d3e
