### ISSUE TITLE
There is no jobs saved??

### ISSUE THREAD

**Issue by markie1611** [Zrips/Jobs#1656]
I ran the /job archive command and for myself it worked fine, but for another user it was showing No jobs found.

The user is a lvl 9 farmer and has player multiple sessions with their data being saved between sessions and server restarts. 

When i ran the /job archive [other user] command it showed the same - no job found. 

There is no error in the console, or any indication why the other user couldn't retreive their data, even though as I say the data is clearly being stored.

I've attached a screenshot of how it appears, first with my stats and then the reply when I tried it for the other user. 
![image](https://github.com/Zrips/Jobs/assets/21036524/fd6ff821-ccc1-497e-a24b-2947fb7b76c8)

**Jobs version:** 
Jobs5.2.1.0.jar

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-181 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7145f41)

**Relevant plugins (Delete if this isn't needed):**
just Jobs Reborn.

**Comment by StarGamerShalom** [comment]
I think I am having something similar happening. Every time server restarts player jobs seem to disappear. I see that the job name in scoreboard goes to none but it still has the previous job points even if change it to a different Job. Not sure what to do but every time I restart server the job disappears. I am using MySQL database so not sure what is going wrong. No errors in console for me too.

**Comment by markie1611** [comment]
Thanks for the feedback, but I dont think our problem is the same. it sound to me that your issue is the MySQL DB isn't receiving the data and there are local variables being saved. So when the server restarts a small amount of data remains, but everything else is wiped. (With no knowledge of how this plugin works) My advice would be to check that your /read/write settings are set up correctly for Jobs to be able to write to the DB, failing that check there are no conflicting table names blocking jobs from writing to the correct place. 

I dont have a SQL DB on my server, not running bungeecord yet, but I am running Geyser for Bedrock access, and it is the Bedrock players it is affecting. So I am guessing it is that which is causing the problem, so I'm hoping there is a solution to any Geyser/Bedrock issues, but understand if its not something I can get help with.

**Comment by StarGamerShalom** [comment]
No worries thanks for the response I found my issue and fixed it. But I too have a Geyser Crossplay setup so hopefully as get more Bedrock players we do not have a lot of problems. We will see. Yeah my first time installing plugin but I'll learn it more as go.

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 19, 2023 at 7:27 PM, ***@***.***> wrote:   


Thanks for the feedback, but I dont think our problem is the same. it sound to me that your issue is the MySQL DB isn't receiving the data and there are local variables being saved. So when the server restarts a small amount of data remains, but everything else is wiped. (With no knowledge of how this plugin works) My advice would be to check that your /read/write settings are set up correctly for Jobs to be able to write to the DB, failing that check there are no conflicting table names blocking jobs from writing to the correct place.

I dont have a SQL DB on my server, not running bungeecord yet, but I am running Geyser for Bedrock access, and it is the Bedrock players it is affecting. So I am guessing it is that which is causing the problem, so I'm hoping there is a solution to any Geyser/Bedrock issues, but understand if its not something I can get help with.

**Comment by Zrips** [comment]
@markie1611 
There should not really be any separation between players or even server types when it comes to archived jobs. Does your database contain any records about archived jobs for those players you mentioned? How exactly are those players leaving jobs? Can be weird question, but in case you have some 3rd party plugin which does job leaving it might be causing issues by not performing correct job leave process and skipping archiving of the old job.

**Comment by markie1611** [comment]
Ok, so thank you very much, sorry to have wasted your time. There is no problem. It wasn't until you asked how players were leaving their jobs that it made me think - the other player is still in their job - so i forced them out and double checked and it appeared. So thank you, nothing is wrong.
