### ISSUE TITLE
Quests Enhancements

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#166]
**In-Game Enhancement Ideas:** What would be great is if we can enter additional commands for quests with pagination if needed
**/jobs quests start** <**JobName**> - start the quest for JobName 
    **Permission**: jobs.command.quests.admin.start
**/jobs quests stop** <JobName> - stop the quest for JobName 
    **Permission**: jobs.command.quests.admin.stop 
**/jobs quests start all** - start all the quests for all jobs 
    **Permission**: jobs.command.quests.admin.start
**/jobs quests stop all** - stop all the quests for all jobs 
    **Permission**: jobs.command.quests.admin.stop
**/jobs quests list** <PlayerName> - lists all quests for player which would show the JobName, Quest Completed or Incomplete 
    **Permission**: jobs.command.quests.list
**/jobs quests list** <JobName> - lists all quests for JobName which would show all the quests by number, name, action, target, etc
    **Permission**: jobs.command.quests.list
**/jobs quests list all** - list all enabled quests for all JobNames which would show similar to above  
    **Permission**: jobs.command.quests.list
**/jobs quests edit** <JobName> - this would open an edit UI to allow the admin to change the quest details including enabling/disabling  
    **Permission**: jobs.command.quests.edit

**Console Enhancement Ideas:**
Same as above, but no pagination

**Comment by Drewflav** [comment]
Additional quest suggestion here. Would it be possible to have it so a quest has to be completed within a specified region? 

      ``1:
        Name: "Kill Mobs"
        Objectives:
        - Kill;Zombie;64
        - Kill;Skeleton;32
        RewardCommands:
        - "money give [playerName] 250"
        - "msg [playerName] Challenge completed"
        - "playsound minecraft:ui.toast.challenge_complete master [playerName] ~ ~ ~ 100 1.75 1.0"
        RewardDesc:
        - "Rarity: Common"
        - "Task: Kill 64 zombies and 32 skeletons in the arena!"
        - "Reward: $250"
        Worlds:
        - "World_Nether"
        Region:
        - "Arena" 
        Chance: 30``

**Comment by smmmadden** [comment]
Excellent idea @Drewflav - being able to select a region (WorldGuard), Residence and/or Subzone (Residence Plugin) would be a great option to have.

**Comment by montlikadani** [comment]
@Drewflav This can be a **huge large memory leak** to the server, so the server can crash, whatever the server capacity. The server may collapse because _PlayerMoveEvent_ and chunk remain on the server, so it takes up a lot of space and the Bukkit events are only deleted when plugin is disabled.

@smmmadden This is not a good idea because of server ram usage. The same chunk ram digest is in the Explorer job.

**Comment by smmmadden** [comment]
makes sense. Sounds like a bug for Mojang to work out so that isolation can be trapped to specific chunks or coordinates and not cost in performance or memory consumption.

**Comment by montlikadani** [comment]
Yes, this known bug is still for Mojang and does not fix it for some reason, so we need to manually fix it in the plugin code to avoid consuming the server.

**Comment by Drewflav** [comment]
Could it be tied into the restricted areas?

**Comment by montlikadani** [comment]
@Drewflav Hmm.. May be possible

**Comment by montlikadani** [comment]
It's time to announce, added editquest sub-command, which can list the quests and edit them. https://github.com/Zrips/Jobs/commit/0f9ed9e2c6df868e5069038fc91550bd4625495f

For start and stop commands, not sure this needed, but also is not easy to code, because we have a lot of datas, which needs to save/load on plugin stop to/from database and this causing the server slower loading at startup.
