### ISSUE TITLE
!!UNLIMITED JOB POINTS BUG!!

### ISSUE THREAD

**Issue by sennby** [Zrips/Jobs#1715]
I am on 1.20.4, latest jobs version.

Not always, but it seems certain players can unlimitedly purchase things from the job shop store on my server, and the go negative in their balances, they dont see themselves going negative in their account, it never updates or anything, but in console you see them buying and their points going down and going negative.
![image](https://github.com/Zrips/Jobs/assets/138246331/cbf5eb09-6933-4c62-a66c-3844a5244c49)

**Comment by sennby** [comment]
![image](https://github.com/Zrips/Jobs/assets/138246331/ca0d23e9-d13b-404a-b1df-97ab3a87fe36)

**Comment by sennby** [comment]
![image](https://github.com/Zrips/Jobs/assets/138246331/33c7e2b4-9fff-44d7-b8c4-bc7de1fcf7f4)
the user says he hays 7418 points, but it never goes down. on my end it shows nothing of the sort.
If set his points manaully to 800, he doesnt see that happen. I can check via the command and it doesnt work.

**Comment by sennby** [comment]
This seems to only be for select users. I tested on a few others and cannot repeat it.

**Comment by Zrips** [comment]
Messages shown in your first image only appear when using editpoints command which is made for staff members only. Due to lack of command records in console I would assume that this command is being triggered by 3rd party plugin, you should double check your plugin which controls your shop which might not account properly for negative numbers.
