### ISSUE TITLE
API Support to know what job a payment is coming from

### ISSUE THREAD

**Issue by casperwtf** [Zrips/Jobs#1833]
**Description of new idea or improvement on existing one**
Adding JobsPaymentEvent#getJob to the API.

**Detailed information what should do**
When calling the event, add the job that its being called from to the event.

**Comment by Zrips** [comment]
You might want to use JobsPrePaymentEvent instead if you want to get specific jobs. JobsPaymentEvent is fired on batch payment trigger, aka it will include all of the payments due to be given from last cycle, so we don't have reference point on which job made how much, its just an event to inform that player is receiving specific amount of payment in total. 
JobsPrePaymentEvent does have getJob() method.
