### ISSUE TITLE
Permissions per level not working

### ISSUE THREAD

**Issue by ShadowPauler** [Zrips/Jobs#217]
Using the format: https://dev.bukkit.org/projects/jobs/pages/permissions
And the format in the Config, I've tried almost about everything, and nothing has worked.
It's not executing any commands, nor giving me any permissions.

I'm using: LuckPerms + Vault on the latest version of spigot 1.12.2 and the latest version of Jobs Reborn

My buddy told me it could be because LuckPerms isn't officially supported, so I came here.

**Comment by redstonedesigner** [comment]
Just gonna state this in case you need it, “my buddy” refers to me.

**Comment by montlikadani** [comment]
The official permissions are here: https://github.com/Zrips/Jobs/wiki/Permissions
Please send the permission you are having a problem with. (in jobConfig.yml)

**Comment by ShadowPauler** [comment]
That's literally quite like the one above, and I told you, I've done it the same way the config gives me for formatting, and I've made sure it's the correct permission.

Permissions per level isn't working, not the Jobs Reborn permissions. Say like I reach level 2, and I get this permission, I don't get it. Thank you, help is highly appreciated!

**Comment by montlikadani** [comment]
Did you try to use another permission system or just use the LuckPerms plugin? E.g PermissionEx or GroupManager?

**Comment by smmmadden** [comment]
@ShadowPauler - the Jobs plugin you provided on bukkit is NOT the same resource as Jobs on Spigot.  That's the old 2014 files.  Are you sure you are using Jobs Reborn (v4.5.4 - this resource) or Jobs v2.x.
Providing what you have in LuckPerms for how it is configured will help determine if it is a permissions issue or a configuration issue.
Note that Group Manager and PermissionsEx are no longer supported.  I'm using LP v4.5.4, with the latest Jobs Reborn version and perms are working fine on Spigot 1.12.2 and 1.13 servers I host.

**Comment by redstonedesigner** [comment]
The issue is persisting.

**Comment by ShadowPauler** [comment]
Well, any way to fix it, or any recommendation of what permissions plugin to use with jobsreborn? Please, I'll use anything! 😞

**Comment by smmmadden** [comment]
Sorry, but you quoted a resource from Bukkit for "Jobs" by another developer and assumed "Jobs Reborn" is this one and are one and the same - which they are not!

I quote from you: 
**"I'm using: LuckPerms + Vault on the latest version of spigot 1.12.2 and the latest version of Jobs Reborn"**  But you did not list the version of LuckPerms, Vault or Jobs Reborn and as we have no visibility into what your server configuration/setup looks like, we can't assume anything when trying to find a root cause of a behavior issue being reported.  

It could be one or all three plugins mentioned or another plugin causing a conflict.  Paint the bigger picture, so that we can help.

**Comment by ShadowPauler** [comment]
https://timings.aikar.co/?id=364b842532e749518d28a2d1eeb54126

That's all of my plugins.

I forgot to mention, JobsReborn commands per levels also doesn't work.

**Comment by smmmadden** [comment]
now that's great picture painting @ShadowPauler  and very helpful.  Thank you.  So you are only a few builds behind and nothing fixed afterwards would account for the behavior with permissions for leveling up or commands for leveling up to not work.
From the list of plugins I recognized, some are a bit outdated but nothing stood out (to me anyways) that would cause either issue.  So I've got a few questions if you can bear with me.

When the server starts up, are you seeing "any" errors, warnings or plugins not loading of any type? In other words, do you have a clean startup with no issues?
You mentioned using LuckPerms (as I am also), can you share what your permission structure looks like?  I ask because I ran into a scenario where most of the jobs permission nodes had to be at the user level and not at the group level.  I had issues with my complex 7-12 Titles per Job each granted at different levels achieved for 18 Job types I have. This only became apparent when testing I was doing for Jobs Reborn and using PermissionsEx, then GroupManager and finally LuckPerms where I found the issue.  Long winded scenario and it may not be what you have, but seeing how you setup the permissions to match your configuration would help.  Also, if you can provide steps on how to duplicate it, that goes a long way to solving it for Zrips and getting it fixed.

**Comment by ShadowPauler** [comment]
Great. Alright, well my structure is...

The player must join 2 out of 12 - 18 jobs (specifically the 3 harvester jobs in this case), once they join, there's 100 levels, which has 12 nodes, of unlocking new permissions for each one (ranging from 1 - 30 permissions each) but I have only just tested 1 permission node.

For testing, I'm joining a job, which in the configuration shows at X level, I should get this permission, which will allow me to mine a new type of ore. Well, I reach that level in the job, and I mine the new ore, but I don't get the drop that the permission is supposed to give me. So, to make sure it wasn't the custom drops plugin, I added it manually, and it worked. I remove my permissions again, and OP, and I reset my job level and went to the JobsReborn configuration to alter and change it to see if I can get it to work several times. All of the times, I've failed.

Now, I have a major question. For permissions based per levels, does it have to be underneath the job it's created for in the config? Because it would be rediclious if that was so, and I've been wasting my entire time. I also didn't think it would make sense because your able to allow multiple jobs acquire the same permissions based on different levels.

**Comment by ShadowPauler** [comment]
So does that help at all?

**Comment by montlikadani** [comment]
Unfortunately, this permission condition has never been tested for how it works, but I will soon test it whether it works or not.

Adding permission without a separate plugin works with us to use the pluginManager that adds the specified permission to the plugin that has registered for the server's permission system. I do not know if it works for LuckPerms, but I still have a lot of practice on it.
Perhaps, you may need to reload LuckPerms with the `/lp reload` command. But I also know that LuckPerms automatically updates itself.
When you checked the permission with you, _group.owneradmin_, did you consider that the server gave the 3 permission to the owneradmin group?

**Comment by montlikadani** [comment]
Okay, now I've tested and permission per-level worked for me.
I have given you this to work properly:
```
    conditions:
      first:
        requires:
        - j:Woodcutter-2
        - p:jobs.join.Woodcutter
        perform:
        - p:essentials.fly-true
```
I began to do this and add LuckPerms to the _jobs.join.Woodcutter_ permission. Then I joined the server and raised the job to level 2 (no command) and if level 2 reached (which was set), it did not immediately add permission but when I reached level 3 it added.
I also experienced that, not to add permission to LuckPerms.

**Comment by smmmadden** [comment]
hey, thanks for the quick reply.  I think there would need to be explicit support built into Jobs for this to work with different permission systems as the commands to enable/disable the permission nodes vary.
There isn't a need to do an /lp reload since the permissions I added are available immediately upon joining the game.  I do not have luckperms auto-updating the version since I test each release first.

I setup the "default" group which is the parent for "owneradmin" with these three permissions set to false.  The "true" nodes do not exist in the owneradmin, default or smmmadden (my user). So they were not added.  I would only expect that Jobs be adding the permission nodes to the user, not the group since that would enable something for all users.

The equivalent command if I did this in LuckPerms would be:
/lp user smmmadden permission set ridables.allow.ride.chicken true server=world world=world
/lp user smmmadden permission set ridables.allow.ride.cows true server=world world=world
/lp user smmmadden permission set ridables.allow.ride.pig true server=world world=world

The config I have is identical to what you provided.  You are saying that your user has the permission of essentials.fly true and your default group still has essentials.fly false?  That's the test I'm working on which does not work.

**Comment by montlikadani** [comment]
Unfortunately, I do not know why not adding Jobs to LuckPerms permissions because it does not add to the LP for me. This could be improved by hooking LP to Jobs and retrieving the LP database to include permissions. But since there are plenty of permissions schemes, it will not be added.

No. If the configuration is set to true for permission, then the player gets it, but if false it is not.

**Comment by smmmadden** [comment]
I'm confused - are you saying it worked or did not work?

Also - I'm reading that Jobs does NOT support LuckPerms.  Is this correct?

**Comment by montlikadani** [comment]
Sorry. I said it worked.

No. The plugin support for all permission system plugin because we not added to hook into a plugin.

**Comment by smmmadden** [comment]
sorry, must be a language barrier here.  I know Jobs supports multiple permission systems, that's not the question here.  It's specifically for jobConfig.yml where one can add a condition and based on it "perform" the permission (set) whether it be granting or denying that permission.  

When I tested this, it is not working for the permissions setup the same as you but with different plugin (Ridables). None of the permissions that were added in the conditions section were performed including adding - p: essentials.fly-true so I have no idea how it worked for you.  Are you using PaperSpigot 1.13.2 Build 481+ with Jobs 4.9.3+ of 11/18 and LuckPerms 4.3.49?  If you are can you provide a screen shot of your LuckPerms editor showing that the permission was added?

**Comment by montlikadani** [comment]
I'll tell you more clearly.
Adding permission did not work for me, just like you did, and Jobs did not give permission to LP.
I using PaperSpigot 1.13.2 Build 483 with Jobs 4.9.3 (dev version) and LuckPerms dev version. The image would be the same as yours.

**Comment by smmmadden** [comment]
okay - got it now :-)  At least you were able to confirm what I did and what @ShadowPauler was trying to do and that it is not working.  

Can you check with @Zrips to see what/how he expected this to work or whether or not it can be fixed to work? It is documented that it should work.  Question is, how and for what?  Thanks! :-)

**Comment by El-pika** [comment]
Hi, sorry tout dig it up, but is there any updates on this issue ?

I'm trying to work around it with SQL and triggers but this would make everything way more easy !

**Comment by montlikadani** [comment]
After a good while ... We realized (finally) that when Jobs registers new permission names, they can't be added by Bukkit, that is, they can't be integrated into the permission systems database, or the plugin can't accept them. This is not a fix, as a lot of data is still saved in Jobs causing server delays and will not be fixed. Otherwise, this Jobs plugin is not a permission handler, but a job handler.
