### ISSUE TITLE
BossBar not working on 4.8.0 Spigot 1.13/1.13.1

### ISSUE THREAD

**Issue by ValerianV** [Zrips/Jobs#238]
Hello,

I was running jobs 4.7.2 then migrated to 4.8.0.

The BossBar that notify current XP and level for the user stopped to work on 4.8.0.

The cause is 4.8.0 because when i downgrade to 4.7.2 on spigot 1.13 it works again.

**Comment by Nogapra** [comment]
Same

**Comment by CloudeLecaw** [comment]
I can agree that the Bossbar is not Working.

The Bossbar broke with the update to 4.8.0
So lastt Working Version for the boss is 4.7.4


Tested with Spigot 1.13 and Spigot 1.13.1

**Comment by smmmadden** [comment]
@Zrips - any update on this issue?  Thanks, Steve

**Comment by CloudeLecaw** [comment]
Maybe he took it out ;)

Also Zrips is a busy Reallifeman *g*

Well you will see if there may comes any Update about this. For now the Feature is not in there anymore (because its broken ;)) but feel free to use 4.7.4. I saw no disadvantages of using this version in 1.13.1. 

May one day an Update came out that brings this Feature back :D

**Comment by smmmadden** [comment]
the plugin needs to get updated to support the namespaces in 1.13.1 due to all the API changes.  Going backwards to 4.7.4 will only cause other issues that have already been reported.
We are all busy in real life and most of us do this in our own time (what little we have).  I work 7 days a week 12-16 hours each day in my regular job, then I do this for fun. :-)

Not hearing from the developer gives the impression that the plugin is abandoned (even though others are updating it as they can).  I don't believe this to be the case but any response is better than nothing. :-)

**Comment by montlikadani** [comment]
Yes. Zrips can not be online all day and I do not because we are not at home to upgrade the plugin and Zrips 1-2-3 weekly update plugins. I can help him and so he needs to work less.
**I tested BossBar and did not work for me either. So I'm trying to fix it.**

**Comment by CloudeLecaw** [comment]
cant u wait? ^^
rushing him with threads will not help. im sure he will let us know if there is any update ^^

**Comment by smmmadden** [comment]
@CloudeLecaw - it's been nearly a month with no responses or acknowledgements of any kind.  So everyone is getting restless as that is unlike him to not respond.  We (I) at least know he (Zrips) is actively working on his CMI and Recount plugins, but for Jobs and Residence it's been silent. So there is nothing wrong with asking for an update in this case.

**Comment by montlikadani** [comment]
As I said, I'm looking for the problem of why BossBar does not work, but I have not found it yet. There are other bugs and they need to be fixing. You can help fix these problems by opening a Pull Request and we will checking the PR.

**Comment by Blackyvk** [comment]
Is it safe to rollback to an older version which works? i'm on 1.12.2 and the boss bar doesn't work either.

**Comment by Blackyvk** [comment]
This issue also happens on 1.12.2

**Comment by montlikadani** [comment]
Why? I'll tested on 1.12 version and worked correctly for me. And tested in 1.13 but this version not work.

**Comment by CloudeLecaw** [comment]
Well u havent read this trhead Right? 🥉 

Rollback to 4.7.4 because after it brokeor use 4.8.0 without bossbar and wait like we do for a fix :3

**Comment by CloudeLecaw** [comment]
arg..giving me one Hands down also dont bring you a fix my dear

yaou have to wait like we all for a 4.8.1 where the bossbar may be fixed or use 4.7.4 if u cant llife without the bossbar..done!

**Comment by Blackyvk** [comment]
I gave you Hands down because, it seems you arent the one reading, all i see here from you is telling everyone the same thing everytime they reply, kind of annoying you know ?

I'm writing here because it happens in 1.12.2 for me aswell even on a clean setup so he is aware, i know the issue will be fixed eventually... I'm even trying to fix it myself.  I'm not complaining, i'm not trying to rush him to fix this now, i'm very patient.

**Comment by montlikadani** [comment]
_I've released a DEV. version which includes lots of fixes, add new items, and more. [release](https://github.com/Zrips/Jobs/releases), You can test it._

**Comment by Nogapra** [comment]
In the version 4.8.1-DEV and last Spigot 1.13.1 it works again

**Comment by smmmadden** [comment]
also working in PaperSpigot 1.13.1 (Build 355)

**Comment by CloudeLecaw** [comment]
Yeay the bossbar works in spigot 1.13.1 aggain with this dev Build.

Only Problem: on Login i get the meassage that his build is not uptodate and i recomment me to download the 4.8.0 on spigot :3

**Comment by montlikadani** [comment]
@CloudeLecaw 
Same as #257
