### ISSUE TITLE
Hoppers anti Exploit isnt working?

### ISSUE THREAD

**Issue by Blackyvk** [Zrips/Jobs#239]
Jobs 4.5.4
Spigot 1.12.2

This isnt working for me:

  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smellted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true

Players can fill with hoppers and earn money for it, and then take use hoppers to take the items out and make easy money.

**Comment by smmmadden** [comment]
Have you tried with a more recent version of Jobs (4.8.0) ?  Also, make sure you're using the latest 1.12.2 build of Spigot.

**Comment by Blackyvk** [comment]
I just tested with latest Jobs and lastest spigot 1.12.2  and they pay

maybe give us an option to block it completely, like deny the block interactions individually for hoppers and droppers, so the items dont move at all ? because people also abuse droppers for this.

denyHopperInteractionbrewingstand: true
denyHopperInteractionfurnace: true

denyDropperInteractionbrewingstand: true
denyDropperInteractionfurnace: true

**Comment by Blackyvk** [comment]
Oh, I think I found the issue... it's an incompatibility with https://github.com/Minebench/HopperImprovements/

This plugin really improves the perfomance of the server, i wouldnt like to remove it, do you think it's possible to make it compatible somehow?

**Comment by smmmadden** [comment]
based on that projects page, it looks like [PaperSpigot](https://destroystokyo.com/ci/job/Paper/) has addressed the performance issues already.  Is moving to PaperSpigot an option?  Certainly not saying that's the fix, but would be curious if the issues persists because of a spigot bug.

FWIW - I dropped in the 1.13.1 paperspigot jar file, changed my batch file to use it and server started up fine with no other changes needed.  It is a simple drop/replace option.  :-)

**Comment by montlikadani** [comment]
You need to enable `ExploitProtections.Furnaces.Reassign` boolean.

**Comment by Blackyvk** [comment]
no, I mean, this plugin ( https://github.com/Minebench/HopperImprovements ) improves perfomance of hoppers, and changes how it behaves making it impossible for the plugin jobs to detect if an item comes from a hopper, so the anti exploit doesnt work... i was wondering if you could make it work somehow.

**Comment by montlikadani** [comment]
This plugin has been updated for a long time. What @smmmadden said, use PaperSpigot to avoid using the HopperImprovements plugin, because this error is fixed in Paper.

**Comment by Blackyvk** [comment]
but what if I need to keep using spigot because other plugins break on paper ?

**Comment by montlikadani** [comment]
No. Paper describes Spigot's plugins not breaks because compatibles all of them with Paper.

**Comment by smmmadden** [comment]
what he said is that Paper is based off of Spigot with enhancements for Performance that Spigot does not have.  The advantages are greater and if there are bugs with plugins running on PaperSpigot, then they should be reported.  You'll have more success in getting bugs fixed in Paper than you would in Spigot. :-)

You also don't need to build the jar file yourself and can download the jar directly.
