### ISSUE TITLE
Jobs Not Paying

### ISSUE THREAD

**Issue by MrWardy** [Zrips/Jobs#240]
So I have the miner job and I'm not getting anything, I've mined stone, iron, coal. The config is completely default, I literally just reset it in hope of fixing the issue.

**Comment by smmmadden** [comment]
There isn't enough detail here to comment one way or another.  What server are  you using (Paper, Spigot, Craftbukkit, Forge, etc.) or what version and build is it?
Which version of Jobs Reborn are you using?
Are there errors in the logs when you try?
Did you add all the correct permissions?
Did you join the miner job to get paid?
Is the block you were mining also included in the jobConfig.yml? If not you need to add it as not all blocks are included (by default).

**Comment by MrWardy** [comment]
Sorry that's my bad.

Paper 1.12.2

Jobs 4.5.4

No there are no errors, there was one with connecting to MySQL, switched to SQLITE, no errors yet I still don't get paid.

I have * for more permissions

Yes, I am working in the miners job and not getting paid.

Yes, my specific block I am using to test whether I get paid or not is iron, which is indeed added https://i.imgur.com/Ozz4qCy.png

**Comment by smmmadden** [comment]
Are you using at least Vault v1.6.7 and an Economy plugin (SaneEconomy, EssentialsX or some other compatible economy)?
Are you using LuckPerms or another Permissions plugin? Some permissions plugins don't treat the wildcard properly which is why I'm asking for this and the jobs.* is for admins only, so its not the recommended way to test it.  LuckPerms works for my 1.12.2 Paper servers with SQLite and Jobs 4.5.4.

Are any other jobs paying or is this the first time using Jobs? If this is the first time, visit the spigot site for the documentation https://www.spigotmc.org/resources/jobs-reborn.4216

Do you have any other plugins that could be interfering/conflicting with payouts?  What would help answer these questions (and then some) is if you could do a startup of your server and paste the log up to pastebin or some other site that we can review to see if anything else pops out?  Often times, this is the best method to get support for any plugin b/c it reveals a lot more than you may be aware of. :-)
Thanks! -Steve

**Comment by MrWardy** [comment]
I have Vault 1.7.1, EssentialsX and LuckPerms. Also I'm the only one with wildcard permissions. However payment issues don't work for me either.

I have no tested EVERY job, however I have tested Miner and Lumberjack.

https://pastebin.com/Sdxfac2F

**Comment by smmmadden** [comment]
I was referring to the parent level of jobs.* which I wouldn't do.  I look at it this way, as an admin we get access to everything but a typical player will have far more restrictions on what they can/should do and the permission nodes would be specific and not wildcard given.  

Since you are using LP, I exported the perms used in my worlds for jobs and where they go.  Note that the "owneradmin" permission group has jobs permission nodes, but the "default" players permission group does not.  Instead, grant the jobs permissions to each player.  One can argue that's not a very scalable solution but anytime I add more perms to the default group, some commands/options just don't work.  

Here is the script that you can use for default users and admin users so you don't have to do each one line at a time for each of the three worlds (overworld, nether & the_end).  https://pastebin.com/30YdhUVh

Hope this helps! :-)

**Comment by MrWardy** [comment]
I found the incompatibility, it's something about LuckPerms, I'm not sure what though. Would it be the wildcard thing? And if so could you explain that a bit more because I don't quite understand.

**Comment by smmmadden** [comment]
that's probably a better question for Luck to answer, but I can tell you that if you use /lp editor command you'll get a link that will show all the perms added for the groups being used for the server, the world name, server name and context.  Often times, if the server=xxxx and world=xxxxx are not correct you will have issues with whatever permission you added.  What I found most helpful is the editor either for the groups or /lp user xxxxxx editor (where the xxxxx is either the UUID or username).  That will show you exactly what was enable (or disabled) user by user especially if it isn't a global issue and isolated to one or more players.

The other trick/feature I use extensively when creating new worlds or updating with new plugins is the /lp export myPermsList.txt where you get a full dump of all the permissions (similar to what you see in the GUI Editor) but in one text file that you can make changes to more easily.  This is especially helpful if you have a lot of plugins 50+ and/or a lot of permission nodes for each where it will exceed the largest page size and not show all the permissions.    Give those a shot and see if you can narrow down where it is.

Steve

**Comment by MrWardy** [comment]
I know how to use LuckPerms, I'm talking about the incompatibility. So I setup a test server, transferred Jobs, EssentialsX, Vault and LuckPerms to a local server along with all their configs and Jobs didn't work. So I started one by one removing plugins, the first one I removed was LuckPerms and all of a sudden now Jobs works.

You were talking in an earlier message about something with wildcard pemrissions and Jobs not working so well together.

**Comment by smmmadden** [comment]
yes, that's why I shared the permission nodes to compare what you have and where they are.  Given you now know it is something to do with permissions, the wildcard usage may not be picked up.  Especially if you added it to a group (default or something else).  

All the permission nodes need to be at the player level (not group) or issues like these come up.  That's been my experience from 1.10 and higher.  It was worse when I used the now unsupported GroupManager and PermissionsEX and finally found out why when I upgraded to LuckPerms.  Everything was in black in white and worked when I put Jobs permissions at player level and NOT at group level.

**Comment by MrWardy** [comment]
Okay, off the top of your head is there any way to apply a certain to permission node to all players by default? Including new players that join the server?

**Comment by smmmadden** [comment]
yes, you can do that in their default group in LuckPerms.  However, you cannot do it with the Jobs permission nodes which is what we've been talking about.  That's the way all perms should work (hierarchy of groups), but as I said previously, some plugins and/or wildcard use may be problematic which is generally why admin's get it and not normal players.

**Comment by MrWardy** [comment]
So funny story right? It's actually not funny it's really sad, I forgot to add jobs.world.worldname, I'm so sorry for wasting your time, but I will say thank you for being such an active, kind and helpful developer.
