### ISSUE TITLE
Question Cannot find new 1.13 blocks and mobs...

### ISSUE THREAD

**Issue by Phyther** [Zrips/Jobs#244]
I am creating a job and want to use the drowned mob but I can't seem to find it. any suggestions, or does this need to be added?

**Comment by Phyther** [comment]
Also, how can I add the gui ID for the new blocks?

**Comment by montlikadani** [comment]
Unfortunately, there are many ID deficiencies in many entities, as Minecraft did not enter any entity IDs. This page will be followed if a new entity or changed the IDs: https://minecraft-ids.grahamedgecombe.com/entities
Whatever entity you need, you can see [here](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/CMILib/ItemManager.java#L456) that there is no ID yet.
Yeah, and even block and material IDs are missing because they are not given.

**Comment by smmmadden** [comment]
correct me if I'm wrong, but my understanding is the internal ID's (numeric) are being phased out in favor of enum constants (names)?  Or is this that we don't have either for all the entities?
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by montlikadani** [comment]
At us, the enum constant names disappear because we use entities, materials, etc. based on IDs.

**Comment by smmmadden** [comment]
not sure what you mean by "At us" or constant names disappear.
Mojang is purposely removing the numeric ID's and that means anyone else using them downstream would also need to remove them.  This is a positive change but does mean either developers drop support for 1.12.x and earlier if they don't want to maintain both API's or support both and make changes to support 1.13.x and higher.  As of 1.13.1, Mojang still has not finished with this flattening so I suspect we'll have a few releases that will continually break plugins until they are done.

**Comment by Phyther** [comment]
So if I am understanding this correctly, jobs will never add the new blocks because no block ids were provided? Thus any new blocks added to the game will never be useable?

**Comment by cj89898** [comment]
I'm sorry, but I want to add my 2 cents here. This "wontfix" is kind of bullshit. You're using a deprecated method getID() which is provided by spigot. Mojang has been wanting to get rid of IDs for items for AGES and they will not be adding them in any future updates for new items. I think you need to adapt for the changes mojang has decided to implement and actually support 1.13 (and future updates for that matter) fully.

**Comment by smmmadden** [comment]
I agree @Phyther and @cj89898 - this is NOT an option to just close this as not being fixed without a real decision so everyone understands what's at stake.  What I was pointing out is the DROWNED entity, does not have a material name to use.  The only one that is available, is DROWNED_SPAWN_EGG which is not matching up with the entity of "DROWNED" for what the original ask was for.  At least it isn't available in the [spigot code](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) "yet".

The numeric identifiers as I've stated, what Mojang stated and what cj89898 stated is going away permanently, so it comes down to what will be the future direction of this resource?
1. Stop supporting 1.12.2 and earlier and no longer update/fix bugs
2. Continue support for both 1.12.2 and earlier numeric ID's **and** 1.13.x material names for both
3. Create a 1.13.x project for the plugin to fully support new material names ONLY going forward 
4. Continue support/enhancements for 1.12.2 and earlier release ONLY and state the plugin will not be updated to support 1.13.x and higher.
5. Someone forks the code and decides to support it on their own.

I've seen developers choose each of the above, so its a personal choice and whether the developer/author/owner has the time or wants to put the time into future releases.

Since this is @Zrips project, I think the decision is only fair that he decides what the future direction will be and when we can expect progress.  I've been tracking all the 1.13.x updates and there are already 716 that I know of ready to support it so there has been significant progress by many developers to embrace the future.

**Comment by Phyther** [comment]
So you know, the mobs/blocks are supported. After a bit of fiddling I found an error in my config that prevented me from using the new blocks/mobs...

**Comment by smmmadden** [comment]
great investigative work @Phyther :-)

**Comment by cj89898** [comment]
Now I look like a dick... But to be fair I was looking at the Gui Item code, which does not support names I guess.
