### ISSUE TITLE
All TranslatableWords are in English

### ISSUE THREAD

**Issue by DmitryRendov** [Zrips/Jobs#324]
Affected version 4.9.5, clear config.

**Comment by montlikadani** [comment]
What is clear config? If it is clean, it is completely empty, meaning that no settings are found. Make sure you have changed the language in the generalConfig file that you would like to select with the shortened form of the corresponding language. Current languages are found in [this tab](https://github.com/Zrips/Jobs/wiki/Translations).

If possible, send a screenshot of the error in the game.

**Comment by montlikadani** [comment]
A screenshot of what's happening **in the game**? Example in the `/jobs browse` GUI.

**Comment by DmitryRendov** [comment]
that's obvious, all are in English, even if I'm using fr or ru locales - https://clip2net.com/s/3Z0gPYV
The picture above is self-explanatory - all the files are the same and all are in english. is that expected?

**Comment by montlikadani** [comment]
Ok. The Words files have been updated for a long time because of its author, which can cause the error. Since we recently changed the ID and name of the materials because of version 1.13. You can view this in the current _Words_en.yml_ file.
Try to **delete the TranslatableWords folder** (I know you deleted the Jobs folder but you shouldn't) **and run this command**: `/jobs reload` to generate new Words files for you.

**Comment by DmitryRendov** [comment]
@montlikadani I'm ok with this issue, since I keep all the server code in a git repo and I'm cleaning up the Jobs folder just in order to re-generate configuration and compare them with my base and make some alignment after every new release.

The issue will persist for all new users who starts from scratch - even if they remove the folder and run /jobs reload from server console, it just restores all the files, but again all of them are the same and are in English. 

 PS: I appreciate your effort to update the plugin for 1.13 - it looks incredible! Thanks!

**Comment by Zrips** [comment]
b81d5ead6567bd89941ba256d22c0a85d02a5080
