### ISSUE TITLE
Turtle breeding error

### ISSUE THREAD

**Issue by Bedah95** [Zrips/Jobs#354]
Spigot 1.13.2
Jobs 4.10.0

You get no money or experience if you breed turtles.

Breed:
TURTLE:
income: 1
experience: 10

**Comment by Temale62** [comment]
UP

The problem is still relevant in 4.10.3

**Comment by montlikadani** [comment]
It seems that this animal's birth time is very late, so Jobs cannot save the data so that the player who bred them does not get the money until the turtle comes out of the egg. The birth of the turtle also depends on GameRule's randomTickSpeed, so if you raise it, it will hatch faster from the egg. But the player does not get any rewards.
