### ISSUE TITLE
[BUG] Jobs repair exploit

### ISSUE THREAD

**Issue by eUipKh** [Zrips/Jobs#438]
Toggle subs on
https://youtu.be/mKDhwXpdMkw

**Comment by montlikadani** [comment]
This is not really fixable. There is only one solution for the time being and we have to check in Anvil the item that the result would be, so it won't give money.
The problem is, if we give this, but we can't verify that if the same item is in our inventory and we want to fix it, then it will give it rewards. So there is only one solution to this.

**Comment by mrfloris** [comment]
If this can't get fixed, how do I turn this off in Jobs plugin?

**Comment by eUipKh** [comment]
Remove this section: https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L392

**Comment by montlikadani** [comment]
Should fix the latest version.
