### ISSUE TITLE
McMMO abilities multiplier not working with jobs.boost permission.

### ISSUE THREAD

**Issue by markusew** [Zrips/Jobs#439]
***Description of issue:**

When you have a permission that gives you an increased money gain from jobs then that extra gain will not be multiplied with the mcmmo multiplier. Meaning if you for example have the permission `jobs.boost.all.money.1` and a multiplier of 0.2 you will be gaining (job pay * mcmmo multiplier) + (job pay * boost) => 120% of block pay instead of the intended 2*20% pay. Hopefully the multiplier can be added.

**Server Type:**

Paper 620 (1.13.2)

**Comment by sh1mrr4** [comment]
I still encounter this issue with the current job version. That multiplier is especially important for the tree-feller skill, since you can take giant trees down in seconds. However, due to the issue described above, I can only choose between not using the money boost, or disabling that McMMO skill, if I do not want to face severe balancing issues.

TL:DR, it would be awesome if this could be fixed :)

jobs version: 4.15.11
paper spigot: 1.15.2

**Comment by montlikadani** [comment]
You can configure mcmmo multipliers in mcmmo configuration and also in jobs generalConfig.
