### ISSUE TITLE
JobAction in PaymentEvent

### ISSUE THREAD

**Issue by NurPech** [Zrips/Jobs#462]
**Description of new idea or improvement on existing one**
Hi,

I want to cancel the payment if a player is doing a certain action e.g. break some blocks. To do so I need the JobAction and all involved Blocks/Entities/whatever.

**Detailed information what should do what and when**
On my server it is stored which block is placed by a user and which is generated. If a user is breaking a block which is placed by a user, I would cancel the payment. But if the user is braking a block which is not placed by a user, he should gain his payment

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/wiki/API#JobsPaymentEvent

**Comment by UnioDex** [comment]
I don't know why this is closed because that's not the answer OP wanted. JobsPaymentEvent is insufficient right now. We need to know why player is paid. Which job paid for what action? It would be good if JobsPaymentEvent throw job, action and even the related block with the action. For example if a player break a diamond block and get paid for it JobsPaymentEvent should give all this information.

**Comment by montlikadani** [comment]
@UnioDex Open a new Issue and will be implemented, and actually, its free to open a Pull request to implement.
