### ISSUE TITLE
Points not saving on server reboot

### ISSUE THREAD

**Issue by Lewes** [Zrips/Jobs#479]
***Description of issue:**

Job points do not save on server reboot, especially after spending in the shop.

---

---

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Comment by montlikadani** [comment]
Jobs points are saved correctly when the plugin disabled.

Make sure you have configured correctly the database and have access to the file or web.

**Comment by xDacon** [comment]
Job points do save, however if you have a lot of players and spend your points right before a reboot, your points will go back to what they were before you spent them

**Comment by Lewes** [comment]
@montlikadani Hey - any news with @xDacon's reply?

**Comment by montlikadani** [comment]
With a lot of players, of course, yes, some players points are not saved because there is so much accumulated data that SQL/MySQL cannot handle it. However, when you stop, points are saved for players who are already at least one job away. Saving points is done by first removing the player from the table, then generating a new table and inserting the current player's points.

**Comment by montlikadani** [comment]
Seems correct with the latest version.
