### ISSUE TITLE
Problems with the translatable words.yml

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#501]
***Description of issue:**

Hi, for shearing wool im using the colours Light_Blue and Light_Gray and i will get payed for shearing. But in the translatable words.yml is a mistake in the colour section. i m not able to translate the colours Navy and Silver. If im using Navy and Silver in the jobconfig.yml instead, i will not get payed for shearing wool. 
so could you pls fix the linking between Light_Blue and Light-Gray in the jobconfog.yml and the colour section in the words.yml
Thanks a lot

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Part of the words_en.yml

ColorList:
  0-white: '&fWhite'
  1-orange: '&6Orange'
  2-magenta: '&dMagenta'
  3-navy: '&9Navy' <---- Problem with Light_Blue
  4-yellow: '&eYellow'
  5-lime: '&aLime'
  6-pink: '&dPink'
  7-gray: '&8Gray'
  8-silver: '&7Silver' <---- Problem with Light_Gray
  9-cyan: '&3Cyan'
  10-purple: '&5Purple'
  11-blue: '&1Blue'
  12-brown: '&4Brown'
  13-green: '&2Green'
  14-red: '&cRed'
  15-black: '&0Black'
```

**Comment by montlikadani** [comment]
Leave it `light_gray` and `light_blue`, it changed to Navy and Silver half a year ago because of the minecraft version 1.12 it was not able to distinguish colors, but now it seems that a change has occurred above 1.13 so we need to change the names of these two colors. Same issue: https://github.com/Zrips/Jobs/issues/267
