### ISSUE TITLE
Entity Cat appears as Ocelot

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#504]
When using entity `Cat` as a payment method, it shows up as `Ocelot` now, instead of Cat. This was previously fixed, and @Zrips  UN-fixed it. Cats not being treated as their own entity is still a problem in CMI as well. @montlikadani could you pass this on to @Zrips so it can be fixed there, as well?

This was already fixed once from my previous ticket, #480

**Comment by montlikadani** [comment]
![kép](https://user-images.githubusercontent.com/30026208/63212317-cc1c1a80-c102-11e9-82f3-dd84b8594899.png)

**Comment by Zrips** [comment]
There is no such thing as a Cat in minecraft, you have Ocelots. So there is no reason why we should rename something to a different name. You are able to utilize Cat as a variable in config files, but in general, we should show it as Ocelot, because they are Ocelots and not cat's. https://animals.sandiegozoo.org/animals/ocelot

**Comment by Seeroh** [comment]
https://minecraft.gamepedia.com/Cat

@Zrips As of 1.14, a cat is now a separate entity from an ocelot, with a different mob ID.

**Comment by montlikadani** [comment]
Re-added in [this](https://github.com/Zrips/Jobs/commit/88c6d1fc380fe68ea4c04ef1433e262aa3966dc7#diff-2bbefed2dca880e596848b248efa0102) commit.

Also, re-added in CMI.
