### ISSUE TITLE
PreventHopperFillUps does not work in 1.14.4

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#517]
We are several servers to have the same problem!

1.13  if player have furnace linked, put fish ores or other smelting items IN furnace, player GET exp/money, if using hopper, DONT GET anything
1.14  if player have furnace linked, put fish ores or other smelting items IN hopper linked to furnace, player GETexp/money, if using hopper, GET TOO anything

**Comment by montlikadani** [comment]
Well, the logic is that when you open the furnace, it automatically adds a protection system that is saved in Jobs, so the player gets paid if opened the furnace, or if the player didn't open it at all, and that furnace block not saved (delete `/jobs clearownership` command), you will not receive any income. So this working correctly.

**Comment by jere62smi** [comment]
@montlikadani I think you do not really understand the requests, it's been several times that I try to make you understand that the gains using a hopper to an oven works whether or not the option is used in the plugin. It happens by change that when you put a hopper on an oven, it jumps as it should with your option.
It's been several weeks since I have the problem, I even provided you with videos showing you exactly the problem and my config.

**Comment by montlikadani** [comment]
No, I understand only you have not read what I have written clearly. Once again, I understand: So the problem is, when you place a furnace (oven) and a hopper over it, the furnace is saved if `ExploitProtections.Furnaces.Reassign` is enabled in the configuration. So if we try to get the stuff from the hopper into the furnace, the player gets money. However, if the `/jobs clearownership` command removes the furnaces and does not place and reopen them, the player will no longer be paid.

**Comment by jere62smi** [comment]
So if I understand your message correctly, when the player uses / clearownership jobs right after he no longer receives the winnings? (I just tested and I have received a gain in following your message).
Now what I have trouble understanding and how to prohibit earnings compensation when a player at a registered oven and uses hoppers?

**Comment by Gorderok** [comment]
Indeed you do not make the effort to understand, thank you to test yourself. No relation to the /jobs clearownership command in our problem.

**Comment by Zzheyd** [comment]
Same problem for me ...

You don't understand ... if players use /jobs clearownership command ... players dont get any money/xp if are use furnace without hopper fill ups ...

With 1.13.+ version, when PreventHopperFillUps is on TRUE, players get money/xp on smelting ONLY is furnace is not fill up by hopper, and in 1.14.+ does'nt work...

And in 1.13+ dont need use /jobs clearownership command lol, maybe you need try it ... or mb we have to gove a proof ...

**Comment by montlikadani** [comment]
Nobody understands even now. If you put an item to hopper, then DO NOT open the furnace, because you will get paid for smelting and the fill up hopper will not work.

Reproduce:
1. Open the furnace and put the coal.
2. Close the furnace, and open hopper above the furnace.
3. Put something smelt material to the hopper, close the hopper.
4. Finally, DO NOT open the furnace again, because the hopper fill up will preventing money, if the material moved to the furnace from hopper. So you will not get any income for this.

This tested and works correctly.

**Comment by Gorderok** [comment]
Do you really think that our players are not going to reclick on the ovens for not making money? It will go directly on it to create the bug of non functioning of PreventHopperFillUps : true

Thank you for watching the video that jere62smi sent you on discord.

**Comment by Zzheyd** [comment]
This tested and DONT works correctly ... maybe you need compare work it on  1.13/1.14 ... !

Do not take us for idiots ...

**Comment by Zzheyd** [comment]
"Finally, DO NOT open the furnace again" omg you realy think players DO NOT open again furnace ? lol

-IN 1.13, if player open again and again and again furnace, if option PreventHopperFillUps is on TRUE player DON'T GET ANYTHINK.

-IN 1.14, get xp/money ...

What did you don't understand on this ... ?

**Comment by jere62smi** [comment]
Sorry but I think there must be a bad word but you do not understand our problem. Do you really believe that a player is not going to reopen the furnace to get the money? Anyway, if you can test our problem by yourself, I think you understand our expectations, the currently, your option is useless.

**Comment by Gorderok** [comment]
Do you have a date for a fix?

**Comment by DvN88819** [comment]
I have the same problem on my server but with what I read here I have the impression that you do not give a fuck in fact you should change your glasses and reread the problem to understand, it will help you!

**Comment by IceSaltman** [comment]
I have the same problem on my server, but with what I read, I think you did not care but it's really a big problem you expect 
what ?
