### ISSUE TITLE
Save registered Furnace / Brewing Stands in MySQL Database

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#523]
**Description of new idea or improvement on existing one**

The Idea is to implement an option in the generalConfig.yml like:
StorageMethodMySQL: true/false
If true the registered Furnaces and Brewing Stands will be stored in the MySQL-Database or if false
it will be stored in the .yml file
Pls pay attention for Bungee-Cord Users!!!!!!

**Comment by BlueSoapTurtle** [comment]
I don't see why this is needed, isn't it fine to register x amount of furnaces on ServerA and x amount on ServerB? 
Or are you trying to limit it overall?

**Comment by Sulort** [comment]
no, its not fine. when you are using a bungeecord-network, then a player will not get money from the furnaces, when the furnaces are on server A and the player is on Server B. You only get payed when you are on the same server, where the furnaces are placed and registered.

**Comment by montlikadani** [comment]
Trying to save furnace/brewing data to MySQL is a big risk because if you have a lot of players on the server and everyone is using furnace/brewing, for example, the data will be saved when the server crashes (which is good), and if it takes a lot of data to save to the MySQL database, it takes a **long time** to stop the server. Even this server may freeze.
Otherwise, I don't understand why users want the feature that furnace/brewing data access the saved data via bungeecord when it makes no sense.

**Comment by jere62smi** [comment]
I had proposed this posibility some time ago on the discord and I had said that it will be complicated to put this in place.
The simple reason why we want this option is to really control the furnaces and stills on both sides of our bungee for multi-servers and this synchronization is exactly what we expect.

**Comment by montlikadani** [comment]
I don't see the point why it should be because yaml loads faster than sql because you don't have to ask for an access request which slows down the loading.

> when you are using a bungeecord-network, then a player will not get money from the furnaces, when the furnaces are on server A and the player is on Server B. You only get payed when you are on the same server, where the furnaces are placed and registered.

Well, that doesn't make sense, because if you have Jobs on one server, but also on other B and C servers, you can't save the same block location to get paid.
