### ISSUE TITLE
Placement and Mining exploit

### ISSUE THREAD

**Issue by capfan** [Zrips/Jobs#557]
It seems that blocks not listed as -1 in restrictedBlocks.yml can be used to clear exploit protection for blocks that are listed in restrictedBlocks.yml

Methodology:  Place a block not listed as -1 in restrictedBlocks.yml.  Wait for your configured cooldown and mine the block.   Place a block with income potential.  Wait for your configured cooldown.  The player can now mine the block for income.

**Server Type: Paperspigot

**Server Version: 1.14.4

**Comment by WhatsTheBadNews** [comment]
So, basically in the default jobs config, you can:

1. Place a stone block
2. Mine the stone you just placed with a silk touch pickaxe
3. Place a diamond ore in the location of the stone you just mined
4. Mine the diamond ore you just placed with a silk touch pickaxe
5. Repeat 1-4

Quick and easy exploitative income.

**Comment by Sheepotastic** [comment]
We're getting this issue as well, it's quite a severe issue, but a temporary solution for those curious would be to make the job give negative money for placing the item. This isn't a good solution cause with digger and miner, placing stone or dirt, which is common to do, results in reduced balance, but it's necessary for the time being.
Hopefully this will be fixed soon.

**Comment by montlikadani** [comment]
This makes no sense and does not need to be improved. If you place one block, wait for the cooldown to expire, break it, put another down, so the block duration changes. Even if we try in the same place, there will be a payment delay for each block anyway. If the position of a block has changed, it is no longer considered a protected block because it does not make much sense. Thus, protection on other blocks can be canceled if the previous block has been broken and the type has also changed.
