### ISSUE TITLE
Feature: Timed payouts instead of per actions

### ISSUE THREAD

**Issue by Naskel** [Zrips/Jobs#635]
This is a highly requested feature by the players from my server.
Currently all jobs are paid per action. This is not ideal for jobs like Builder because it heavily favors spamming blocks instead of actual building.

It was possible to make some job payouts based on timed intervals this would help a lot.
For example a configurable interval for a job could be 1 second. If the player does more than 1 action within 1 second, they still only get paid for 1 action. This means long continuous building pays equal to a player aimlessly spamming blocks.

I really hope this will be considered as it's a highly requested feature by hundreds of players and I believe other servers will benefit from this feature as well.

**Comment by montlikadani** [comment]
The plugin already has a timed payout with no multiple rewards, only boost. To stop player from paying for placing blocks in one place, you can use the `PlaceAndBreakProtection` option, which adds a timer or protection if a player has already broken that block or done something about it. If a player does more work, but with more actions, still have to pay, there is no exception, because if you prevent the player from doing something in Action 2, the player will consider it a mistake.
