### ISSUE TITLE
Silktouch mining improvement

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#644]
**Description of new idea or improvement on existing one**
It would allow players to get paid when mining iron and gold ore with a silktouch pick while still preventing them from getting paid for breaking other ores.

**Detailed information what should do what and when**
It would only allow getting paid via Iron ore and Gold ore

**Comment by montlikadani** [comment]
Well, this is what the `PlaceAndBreakProtection` option does to prevent blocks from being repeatedly attempted. I don't think any more changes are needed to the current silktouch protection because the blocks can be set in the restrictedBlocks file and you will not be paid for the blocks in the list.
