### ISSUE TITLE
JobsGUI

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#665]
Would it be possible, for the sake of rp, add an option to not be able to join the profession through the jobsGUI menu of / jobs Browse? (with the right click or the left click according to the config)

**Comment by montlikadani** [comment]
Be config option or permission?

**Comment by Gorderok** [comment]
Config option is better i think :)

**Comment by Nogapra** [comment]
Simply set up the permission node jobs.command.browse negatively and your players will not have access to the GUI

Adjusting this setting with an option in the configuration file would be more complicated (I think) because there is no GUI to change the configuration of the plugin in play. 
It is absolutely necessary to edit the file .yml and re-upload the file and then recharge the config hoping not to have made any other changes that would just broken the initial configuration)

The permission system just tap an In game command and it's ready

Ce n'est que mon avis :)

**Comment by montlikadani** [comment]
@Nogapra @Gorderok think no want to disable the gui feature in game, just want to prevent joining to job from gui. Also the configuration will update automatically if there is any changes if the user updated the plugin and the file will not broke when updating.

**Comment by Nogapra** [comment]
from a general point of view touch the config file (during a plugin maj or just change an option) is always dangerous ^^

always in my opinion for PR the function of the GUI is useless:

Detail of jobs in a book - employment contract
join the job by ordering in game - signing the contract

If you want to add an option in the config to do that this is not a problem, just one more thing to test before updating the plugin on the production servers :)

**Comment by Gorderok** [comment]
Yes I do not want to deactivate the GUI but just prevent joining the trades through this menu. My players have to go to a specific building to take a job.

**Comment by montlikadani** [comment]
@Nogapra I don't think there is any danger in changing the configuration option, since the more options there are in a configuration that need to be loaded, it only reduces the plugin's performance, but in a very small proportion that the server didn't even notice it. Thus, the in-game configuration changes to the GUI would only be needed if they were to work without plugin loading.

**Comment by Gorderok** [comment]
In this menu, I also have an error when I click on one of the trades. May be there are too many items?
https://pastebin.com/eZv5FRhY
Do you want me to open an issue for this?

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/commit/079b0db08d237c86eb1a1e0a810b1576c8f1227b

**Comment by montlikadani** [comment]
@Gorderok You are using PacketEventCatAPI as packet modifier, which prevents handling gui items, and setting stack to 54. You should report to the plugin developer. Without this plugin should works.

**Comment by Gorderok** [comment]
I was tryed without PackEventCatAPI and i was same bug : https://pastebin.com/sM8bMABP

**Comment by Gorderok** [comment]
May be there are too many action in this job. I was try reduce many action in this job and work find, but the return button disapear.
![2020-02-06_19 56 41](https://user-images.githubusercontent.com/43994828/73969131-1dbb9a00-491b-11ea-929a-faa5af78b7cd.png)
If I add actions, I get the error message again and the interface does not open. We should add the possibility of having several pages for a job.

**Comment by montlikadani** [comment]
You should open a new issue about this error.
