### ISSUE TITLE
Restrict using of blocks (break/place/use)

### ISSUE THREAD

**Issue by Matthysse** [Zrips/Jobs#683]
It would be nice for every job to set a white-list of exclusive blocks he can use. (if we set a block in the white-list, it is automoatically prohibited for other jobs to use it). This idea comes from the new blocks from villagers from the 1.14 Minecraft update.

For example:
The fisherman is the only job where players can use the fishing rod.
The florist is the only one who can plant flowers in flowerpots.
The blacksmith is the only one who can use the anvil.
......

**Comment by montlikadani** [comment]
Well, if you do not put the fishing rod in the specified job and action, then obviously will not feel that it is in it because it is not added. If the fishing rod is added to the action, you will be paid if you fish. It would not make sense to prevent the materials from being used in other jobs, because if you do not add them to the list there is no payment.
