### ISSUE TITLE
Players not getting payed

### ISSUE THREAD

**Issue by AshtonMemer** [Zrips/Jobs#695]
When a player performs a job action (ex. cutting down a tree in the Woodcutter job), they do not get paid or earn job experience. However, players with op are able to earn XP and job experience just fine. It seems like I am missing a permission, but I cannot figure out what. Players already have jobs.use and `jobs.use` and `jobs.join.Woodcutter`.

**Comment by montlikadani** [comment]
Check these:
- Make sure that you have Vault and Essentials (or cmi) plugin.
- Make sure you have using the CMI and Vault plugin, if using CMI, then you should enable the Vault economy integration in cmi configuration and downloading the CMI version of Vault if necessary.
- Make sure you have added the `jobs.world.worldName` permission to your group to get income. (`worldName` is your world where the jobs should pay)

The payment are still worked and there is no issues with it. If these tasks are not work, then double check, because it should works.
