### ISSUE TITLE
Support ItemsAdder Blocks/Items

### ISSUE THREAD

**Issue by spathizilla** [Zrips/Jobs#739]
**Description of new idea or improvement on existing one**

ItemsAdder is a plugin which adds custom blocks and items into minecraft through the use of resource packs and nbt tags for custom models. I'd love if we can use Jobs with ItemsAdder to adjust payout of those blocks and items

**Comment by a7ssan** [comment]
+1

**Comment by montlikadani** [comment]
Literally adding this currently seems to impossible because without buying this resource can't possible to add as a new dependency. https://itemsadder.plugin.ga/developers/java-api

This just list out the current available methods/classes. This author literally not allows for developers to use their api for free use. So this issue closing, until there are no any free maven repo or at least a free api version in jar.

**Comment by SirCraftypants** [comment]
> 
> 
> Literally adding this currently seems to impossible because without buying this resource can't possible to add as a new dependency. https://itemsadder.plugin.ga/developers/java-api
> 
> This just list out the current available methods/classes. This author literally not allows for developers to use their api for free use. So this issue closing, until there are no any free maven repo or at least a free api version in jar.

You don't need this, you just need to make Jobs Reborn compatible with custom model data, a few Dev's of premium plugins i use quite easily make their plugins compatible with Itemsadder, i helped them do it by providing them with how the custom model data and NBT is structured.

+2 I use both Itemsadder and Jobs Reborn and need this issue re opened and am willing to help best i can.

**Comment by azox201dev** [comment]
How can i do exemple a ore with a custom texture and its a Diamonds and in the jobs reborn how can change the value of This ore specifitly to get more xp than a normal diamond it's what i want to do
