### ISSUE TITLE
Quests - no save on restart

### ISSUE THREAD

**Issue by Bedah95** [Zrips/Jobs#756]
After a server restart, the previous quest progress is not loaded correctly. If a quest was completed before the restart, it can be completed again after a restart. 
Display in "/jobs quests" is then sometimes incorrect.

Tested with multiserveroptions and sqlite/mysql.
Same results.

Paperspigot: git-paper-168 and git-paper-213
Jobs: 4.15.7 and 4.15.8

**Comment by HuskerFan34** [comment]
I'm having the same issues of quests being able to be completed again after a restart.

**Comment by Yorkiee** [comment]
Same problem here :(

**Comment by Zrips** [comment]
8288c83d0009968393c3afa31bf586f967ff04ef

**Comment by Bedah95** [comment]
still an issue in 4.15.9

**Comment by Bedah95** [comment]
Example:
https://youtu.be/hWqLDPDhMKo

**Comment by montlikadani** [comment]
Do you have `maxDailyQuest` option set in jobConfig?

**Comment by Bedah95** [comment]
Yes:
    maxDailyQuests: 3
    Quests:
      Hellboy1:

**Comment by HuskerFan34** [comment]
I'm having the same issue still after updating as well. I tried both mysql and sqlite after updating and the issue wasn't fixed. Quests will show as "completed" after a restart but will give the reward again if one of the quest actions is performed. 

For example, you could have a quest to "mine 50 stone." I can mine 50 stone and complete the quest before restart and earn the reward. After restart, all I need to do is mine 1 stone and I get the reward again. It pretty much makes quests unusable as you can get a reward every restart instead of every 24 hours.

**Comment by Zrips** [comment]
5a9fa84b6e6c087c61af79722fcf48dff5cfba3b
This should do it.
