### ISSUE TITLE
Dunno if this is allowed but I have a question and no one in your support discord is responding. :)

### ISSUE THREAD

**Issue by awesomek29** [Zrips/Jobs#817]
So I was wondering how the equation _5000+5000*(totallevel/100)_ works and how to specify the amount of pay increased as you rank up each level. I also wanted to know if its possible to make exp gain harder over time like in vanilla minecraft?

**Comment by montlikadani** [comment]
Equations is used to calculate how many income/level/points/exp will grant to your economy bank when you do something in the specified job. It is not recommended to change these values, because these default values are works correctly and shouldn't require any changes. There is another options in generalConfig which manages how often the payout works.
