### ISSUE TITLE
Add more quests flexibility

### ISSUE THREAD

**Issue by IgnisCraft** [Zrips/Jobs#854]
**Description of new idea or improvement on existing one**
I currently have about 15 quests for each job. I want to be able to have my players complete up to 15 quests a day, but only have 3 or so active at a time. They would have to complete one of the 3 active quests before receiving the next one. It would help with the clutter when a player has 3 jobs and 3 quests for each, and I wanted to take the concept of mini, easy quests that can be done in about 10-20 minutes, and the player can keep doing quests all day as they complete them and get new ones.

**Detailed information what should do what and when**
Add a spot in the config maybe to allow us to specify how many quests the player can be actively working on at once.
    rejoinCooldown: 10
    maxDailyQuests: 15
    maxQuestsAtOnce: 3

something like that?

Also, just a suggestion, maybe separate the jobs quests instead of them all being sandwiched together on /jobs quests?
like:
Lumberjack
- quests
Miner
- Quests

**Comment by montlikadani** [comment]
I don't see the point in that. Are you saying your players can’t complete more than 15 quests in one day because they can only do 3? Well, what you set to 15, they can no longer do that day and then complete another 15 quests the next day. If we overwrote this with another option, it would not make sense, as there are 15 maximum quests and there can only be 3 at a time, the player could only complete 3 quests out of 15 quests in one day.
