### ISSUE TITLE
NAN Prices

### ISSUE THREAD

**Issue by blakedj012** [Zrips/Jobs#857]
https://gyazo.com/158a4f4bfa41decfc61e454d5acb29f0

When i see Jobs Infos then i see nan prices like the screenshot.

Latest Jobs Reborn Version
Spigot 1.16.1

**Comment by montlikadani** [comment]
You have dynamicPayment enabled in generalConfig. Disabling will fix it

**Comment by dandud100** [comment]
How is this closed? It is still an issue in the newest version. This issue happens when no players are in a specific job. Meaning that jobstotalplayers - 1 will output -1 which will break the equation. Similarly with only having a single player in a specific job, then same principle applies jobstotalplayers - 1 will now output 0, which of course will also break the equation.
