### ISSUE TITLE
Add a “maxjobs” variable for the equations

### ISSUE THREAD

**Issue by christaylor201** [Zrips/Jobs#883]
#### Description

I think it would be nice to have a `maxjobs` variable for the equations. Why? At the moment it's not possible to calculate the ratio between the maximum amount of jobs a player can have and the amount of jobs a player currently has (well, it's partially possible but all the player groups would've to share the same maximum jobs limit).

This would be useful to apply the model: “The more jobs a player has, the less money he makes.” That way players could also be encouraged to have only the jobs they actually use.

#### Detailed information

Let's say we have a very simple equation, just to show what I mean:
```yaml
income-progression-equation: baseincome * maxjobs / numjobs
```
I think there's nothing more to say; the new variable would return the same value as `%jobsr_maxjobs%` placeholder.

**Comment by Zrips** [comment]
But default equation already does that by including ` * ((numjobs-1)*0.05))` where you will loose 5% for each extra job you have after first one. So having 5 jobs will lower every payment by 20%. So by default players are being encouraged to have as little jobs as possible to increase main money gain instead of joining all of them at once, which in this case with 12 jobs would lower income by whooping 55%

**Comment by christaylor201** [comment]
Yes, I know this part of the default equation already does that in a certain way, but it's not quite exactly what we'd like to achieve.

Here's another example, hopefully better, to illustrate what I mean:
```yml
income-progression-equation: baseincome + (baseincome / maxjobs * (maxjobs - numjobs))
```

You can't do something like this right now if you have multiple groups with different maximum amount of jobs, that's why I'm requesting the new variable.

**Comment by christaylor201** [comment]
Thank you for adding this, I can't wait for the next release!
