### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by LucidAPs** [Zrips/Jobs#905]
Tuinity
MC 1.16.2
Jobs Reborn 4.16.1

Using Aikars Startup Flags

[overview.pdf](https://github.com/Zrips/Jobs/files/5154354/overview.pdf)
[leak.pdf](https://github.com/Zrips/Jobs/files/5154355/leak.pdf)

**Comment by montlikadani** [comment]
Tuinity is not a supported thing, use Spigot/Paper. Also you literally have lot of jobs saved in jobConfig which saves to the memory to successfull loading. Another thing, `The class "com.gamingmesh.jobs.Jobs", loaded by "org.bukkit.plugin.java.PluginClassLoader` which is good and normal thing. Closing, because fixing this, may break the jobs saving/loading to the memory.

**Comment by LucidAPs** [comment]
I have the default jobs that are shipped with the default config nothing more and nothing else. You are in denial if you think your problem is Tuinity.
