### ISSUE TITLE
"all" identifier for shear action

### ISSUE THREAD

**Issue by kikelkik** [Zrips/Jobs#966]
**Description of new idea or improvement on existing one**

It whould be nice if the Action "Shear" whould not just receive black, green, white, etc. but also "all" to configure one income for every color.
Often, all colors of sheeps have the same worth, so there is no need for differentation.

**Comment by montlikadani** [comment]
Specify `wool-all`

**Comment by kikelkik** [comment]
This only works for Break, Place, etc. Actions but not for Shear.
Here's an excerpt of jobConfig.yml:
`    Shear:
      Black:
        income: 4.38
        experience: 4.38
      Blue:
        income: 4.38
        experience: 4.38
      Brown:
        income: 4.38
        experience: 4.38`

**Comment by montlikadani** [comment]
As far as I know `:all` should works as you implemented this last time:
https://github.com/Zrips/Jobs/blob/58bcb0d45aa1594ab54f7ba3e480c57f3455360d/src/main/java/com/gamingmesh/jobs/config/ConfigManager.java#L625-L628

**Comment by kikelkik** [comment]
This break makes the difference between Break and Shear:
https://github.com/Zrips/Jobs/blob/58bcb0d45aa1594ab54f7ba3e480c57f3455360d/src/main/java/com/gamingmesh/jobs/config/ConfigManager.java#L412-L415

I think there's some stuff more to do because Shear seems to receive just the colors (black, white, ...) and not "wool" because it refers to the color of the sheep I click on.

**Comment by montlikadani** [comment]
This currently seems to be very hard. I have this test currently:
```java
if (actionType == ActionType.SHEAR) {
   if (myKey.startsWith("color") && (myKey.endsWith("-all") || myKey.endsWith(":all"))) {
      //subType = ":all";
      meta = "ALL";
      type = myKey.split(":|-")[0];
   } else {
      type = myKey;
   }
}
```
So if we have `color-all` given in the jobConfig, at the loading this will initializes the `type` as `color`. But literally we don't want this as a result. We should include all the existing colors into it. After player shears for example a gray dyed sheep, it will not give payment, because the `jobInfo#getName` (returns `color`) and the `actionInfo#getName` (returns the sheep color) is not the same.

To mention: I don’t think we need an `-all` ID for sheep colors because there aren’t too many colors to never do with adding. I would rather not add this because 16 lines of color is not so much.
