### ISSUE TITLE
Pagination on leaderboards is inaccurate

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#975]
**Plugin version:** 4.16.2
**Description of issue:**
When using /jobs top & /jobs gtop the pagination is completely inaccurate.
It's a little hard to explain and hopefully the images attached are clear enough to understand the issue.

**/jobs gtop**
Only showing 1694 players out of the over 6000 registered users.
![jobs-report2](https://user-images.githubusercontent.com/19877696/97049896-b7e07280-157c-11eb-8495-dd1ce79fd953.png)

**/jobs top miner**
Showing only 50/1170 players that are in the miner job and not showing all pages.
Additionally, sending the "shows top players by job name." messages is different than the one above in /jobs gtop
![jobs-report3](https://user-images.githubusercontent.com/19877696/97049904-badb6300-157c-11eb-9b65-6631a9172744.png)

**Comment by mrfloris** [comment]
I can type jobs gtop and get the first 15, i can't click on pagination because it doesn't work when using scoreboard, i have to use the command. Once guessing the numbers like jobs gtop 50 or 25 or 12, i get no info, but when i pick 8 it shows results, but that's like 120 users, the database shows records for thousands.

<img width="643" alt="Screenshot 2020-10-24 at 13 19 45" src="https://user-images.githubusercontent.com/28841349/97080441-97a3c880-15fb-11eb-816c-a1c4553b7a93.png">

**Comment by Zrips** [comment]
9adcc1593e99f3d1d632940dcf70ddba95ea8b15
