### ISSUE TITLE
Players sometimes have multiple entries on /jobs gtop 

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#976]
**Plugin version:** 4.16.2
**Description of issue:**
/jobs gtop sometimes shows the same player in 2 different rankings.

Might be in relation to Issue #974 

**/jobs gtop - Page 1**
As shown in this screenshot, the player "clark751" is number 10 and the player "Asinine_" is number 11 in the rankings.
![jobs-gtop-double-entry-1](https://user-images.githubusercontent.com/19877696/97050520-cc713a80-157d-11eb-85c3-be29f37c6b42.png)

**/jobs gtop 2 - Page 2**
As shown in this screenshot, the same players now have a higher rank even tho nothing changed.
![jobs-gtop-double-entry-2](https://user-images.githubusercontent.com/19877696/97050618-fa567f00-157d-11eb-8539-f1dd4d5bf44b.png)

**Comment by mrfloris** [comment]
I cannot confirm this, BECAUSE, i cannot paginate to the second page. Because of the scoreboard. 
<img width="1424" alt="Screenshot 2020-10-24 at 13 10 53" src="https://user-images.githubusercontent.com/28841349/97080302-9756fd80-15fa-11eb-8be2-b99b6e6a1314.png">

clicking in-game on the 2 >>>, doens't do anything, i have to type it manually 
<img width="509" alt="Screenshot 2020-10-24 at 13 11 07" src="https://user-images.githubusercontent.com/28841349/97080310-aa69cd80-15fa-11eb-8f18-42ad159eaee0.png">

<img width="1343" alt="Screenshot 2020-10-24 at 13 12 12" src="https://user-images.githubusercontent.com/28841349/97080313-ad64be00-15fa-11eb-930c-abb045fad0ff.png">

**Comment by Zrips** [comment]
9adcc1593e99f3d1d632940dcf70ddba95ea8b15

**Comment by mrfloris** [comment]
Thank you zrips for looking into this one.
