### ISSUE TITLE
Sickle Plugin Integration for Farmer

### ISSUE THREAD

**Issue by silentnyte** [Zrips/Jobs#992]
When single click right click harvest and plant give configurable percent credit similar to mcmmo. Currently you get no credit for the harvest or the planting.

https://www.spigotmc.org/resources/sickle-harvest-crops-with-a-right-click.29443/

**Comment by montlikadani** [comment]
Because that plugin not fires `BlockBreakEvent` on right clicking plant. Literally we're not going to add this resource as a new dependency. We have tons of dependency and it takes long time to get the request from the repository site. You should talk to the developer of that harvest plugin to fire `BlockBreakEvent` on right clicking.
